ALTER TABLE OH_MEDICALDSRTYPE 
ADD COLUMN MDSRT_CONDITIONING VARCHAR(100) DEFAULT 'NULL' AFTER MDSRT_LAST_MODIFIED_DATE,
ADD COLUMN MDSRT_SHAPE VARCHAR(100)  DEFAULT 'NULL' AFTER MDSRT_CONDITIONING,
ADD COLUMN MDSRT_DOSING VARCHAR(255)  DEFAULT 'NULL' AFTER MDSRT_SHAPE;