ALTER TABLE OH_DEATH MODIFY COLUMN DTH_LOCKER_NUMBER INT NOT NULL;

ALTER TABLE OH_DEATH ADD CONSTRAINT FK_DEATH_LOCKER_NUMBER FOREIGN KEY (DTH_LOCKER_NUMBER) REFERENCES OH_BODYCOMPARTMENT (BC_ID);

ALTER TABLE OH_DEATH MODIFY COLUMN DTH_DISCHARGE_DATE DATETIME;