ALTER TABLE OH_DEATH CHANGE DTH_LOCKER_NUMBER DTH_BC_ID INT NOT NULL;

ALTER TABLE OH_DEATH ADD CONSTRAINT FK_DEATH_BC_ID FOREIGN KEY (DTH_BC_ID) REFERENCES OH_BODYCOMPARTMENT (BC_ID);

ALTER TABLE OH_DEATH MODIFY COLUMN DTH_DISCHARGE_DATE DATETIME NULL DEFAULT NULL;

UPDATE OH_MENUITEM SET MNI_CLASS = "org.isf.mortuary.gui.DeathBrowser" WHERE MNI_ID_A="deaths";