
--
-- Definition of table oh_reductionplan
--

CREATE TABLE OH_REDUCTIONPLAN (
  RP_ID INT(11) NOT NULL AUTO_INCREMENT,
  RP_DESCRIPTION VARCHAR(100) NOT NULL,
  RP_OPERATIONRATE FLOAT NOT NULL,
  RP_MEDICALRATE FLOAT NOT NULL,
  RP_EXAMRATE FLOAT NOT NULL,
  RP_OTHERRATE FLOAT NOT NULL,
  RP_LOCK INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (RP_ID),
  RP_CREATED_BY VARCHAR(50) NOT NULL,
  RP_CREATED_DATE datetime NULL DEFAULT NULL,
  RP_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  RP_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  RP_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT FK_REDUCTIONPLAN_CREATED_BY FOREIGN KEY (RP_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_REDUCTIONPLAN_LAST_MODIFIED_BY FOREIGN KEY (RP_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;


--
-- Definition of table oh_otherreduction
--

CREATE TABLE OH_OTHERREDUCTION (
  OTR_RP_ID INT(11) NOT NULL,
  OTR_OTH_ID INT(11) NOT NULL,
  OTR_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (OTR_RP_ID, OTR_OTH_ID)
);

--
-- Definition of table oh_examsreduction
--

CREATE TABLE OH_EXAMSREDUCTION (
  ER_RP_ID INT(11) NOT NULL,
  ER_EXA_ID_A VARCHAR(10) NOT NULL,
  ER_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (ER_RP_ID, ER_EXA_ID_A)
);


--
-- Definition of table oh_medicalsreduction
--
CREATE TABLE  OH_MEDICALSREDUCTION (
  MR_RP_ID INT(11) NOT NULL,
  MR_MED_ID INT(11) NOT NULL,
  MR_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (MR_RP_ID, MR_MED_ID)
);

--
-- Definition of table oh_operationsreduction
--

CREATE TABLE OH_OPERATIONSREDUCTION (
  OPR_RP_ID INT(11) NOT NULL,
  OPR_OPE_ID_A VARCHAR(10) NOT NULL,
  OPR_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (OPR_RP_ID, OPR_OPE_ID_A)
);


INSERT INTO `oh_menuitem` (`MNI_ID_A`, `MNI_BTN_LABEL`, `MNI_LABEL`, `MNI_TOOLTIP`, `MNI_SHORTCUT`, `MNI_SUBMENU`, `MNI_CLASS`, `MNI_IS_SUBMENU`, `MNI_POSITION`) VALUES ('reductionplan','angal.menu.btn.reductionplans','angal.menu.reductionplans','x','R','generaldata','org.isf.reductionplan.gui.ReductionPlanBrowser','N',13);
INSERT INTO `oh_groupmenu` (`GM_ID`, `GM_UG_ID_A`, `GM_MNI_ID_A`, `GM_ACTIVE`, `GM_CREATED_BY`, `GM_CREATED_DATE`, `GM_LAST_MODIFIED_BY`, `GM_LAST_MODIFIED_DATE`) VALUES (351,'admin','reductionplan',1,NULL,NULL,NULL,NULL);