
--
-- Definition of table oh_reductionplan
--

CREATE TABLE OH_REDUCTIONPLAN (
  RP_ID INT(11) NOT NULL AUTO_INCREMENT,
  RP_DESCRIPTION VARCHAR(100) NOT NULL,
  RP_OPERATIONRATE FLOAT NOT NULL,
  RP_MEDICALRATE FLOAT NOT NULL,
  RP_EXAMRATE FLOAT NOT NULL,
  RP_OTHERRATE FLOAT NOT NULL,
  RP_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  RP_LOCK INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (RP_ID),
  RP_CREATED_BY VARCHAR(50) NOT NULL,
  RP_CREATED_DATE datetime NULL DEFAULT NULL,
  RP_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  RP_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  RP_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT FK_REDUCTIONPLAN_CREATED_BY FOREIGN KEY (RP_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_REDUCTIONPLAN_LAST_MODIFIED_BY FOREIGN KEY (RP_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;


--
-- Definition of table oh_pricesothersreduction
--

CREATE TABLE OH_PRICESOTHERSREDUCTION (
  OTHR_ID INT(11) NOT NULL AUTO_INCREMENT,
  OTHR_RP_ID INT(11) NOT NULL,
  OTHR_OTH_ID INT(11) NOT NULL,
  OTHR_REDUCTIONRATE FLOAT NOT NULL,
  OTHR_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  OTHR_LOCK INT(11) NOT NULL DEFAULT 0,
  OTHR_CREATED_BY VARCHAR(50) NOT NULL,
  OTHR_CREATED_DATE datetime NULL DEFAULT NULL,
  OTHR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  OTHR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  OTHR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (OTHR_ID),
  CONSTRAINT FK_OTHERREDUCTION_RP_ID FOREIGN KEY (OTHR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_OTHERREDUCTION_OTH_ID FOREIGN KEY (OTHR_OTH_ID) REFERENCES OH_PRICESOTHERS (OTH_ID),
  CONSTRAINT FK_OTHERREDUCTION_CREATED_BY FOREIGN KEY (OTHR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_OTHERREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (OTHR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

--
-- Definition of table oh_examsreduction
--

CREATE TABLE OH_EXAMSREDUCTION (
  EXAR_ID INT(11) NOT NULL AUTO_INCREMENT,
  EXAR_RP_ID INT(11) NOT NULL,
  EXAR_EXA_ID_A VARCHAR(10) NOT NULL,
  EXAR_REDUCTIONRATE FLOAT NOT NULL,
  EXAR_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  EXAR_LOCK INT(11) NOT NULL DEFAULT 0,
  EXAR_CREATED_BY VARCHAR(50) NOT NULL,
  EXAR_CREATED_DATE datetime NULL DEFAULT NULL,
  EXAR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  EXAR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  EXAR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (EXAR_ID),
  CONSTRAINT FK_EXAMSREDUCTION_RP_ID FOREIGN KEY (EXAR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_EXAMSREDUCTION_EXA_ID_A FOREIGN KEY (EXAR_EXA_ID_A) REFERENCES OH_EXAM (EXA_ID_A),
  CONSTRAINT FK_EXAMSREDUCTION_CREATED_BY FOREIGN KEY (EXAR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_EXAMSREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (EXAR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;


--
-- Definition of table oh_medicalsreduction
--
CREATE TABLE  OH_MEDICALSREDUCTION (
  MR_ID INT(11) NOT NULL AUTO_INCREMENT,
  MR_RP_ID INT(11) NOT NULL,
  MR_MDSR_ID INT(11) NOT NULL,
  MR_REDUCTIONRATE FLOAT NOT NULL,
  MR_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  MR_LOCK INT(11) NOT NULL DEFAULT 0,
  MR_CREATED_BY VARCHAR(50) NOT NULL,
  MR_CREATED_DATE datetime NULL DEFAULT NULL,
  MR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  MR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  MR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (MR_ID),
  CONSTRAINT FK_MEDICALSREDUCTION_RP_ID FOREIGN KEY (MR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_MEDICALSREDUCTION_MDSR_ID FOREIGN KEY (MR_MDSR_ID) REFERENCES OH_MEDICALDSR (MDSR_ID),
  CONSTRAINT FK_MEDICALSREDUCTION_CREATED_BY FOREIGN KEY (MR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_MEDICALSREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (MR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

--
-- Definition of table oh_operationsreduction
--

CREATE TABLE OH_OPERATIONSREDUCTION (
  OPR_ID INT(11) NOT NULL AUTO_INCREMENT,
  OPR_RP_ID INT(11) NOT NULL,
  OPR_OPE_ID_A VARCHAR(10) NOT NULL,
  OPR_REDUCTIONRATE FLOAT NOT NULL,
  OPR_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  OPR_LOCK INT(11) NOT NULL DEFAULT 0,
  OPR_CREATED_BY VARCHAR(50) NOT NULL,
  OPR_CREATED_DATE datetime NULL DEFAULT NULL,
  OPR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  OPR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  OPR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (OPR_ID),
  CONSTRAINT FK_OPERATIONSREDUCTION_RP_ID FOREIGN KEY (OPR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_OPERATIONSREDUCTION_OPE_ID_A FOREIGN KEY (OPR_OPE_ID_A) REFERENCES OH_OPERATION (OPE_ID_A),
  CONSTRAINT FK_OPERATIONSREDUCTION_CREATED_BY FOREIGN KEY (OPR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_OPERATIONSREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (OPR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;


INSERT INTO `oh_menuitem` (`MNI_ID_A`, `MNI_BTN_LABEL`, `MNI_LABEL`, `MNI_TOOLTIP`, `MNI_SHORTCUT`, `MNI_SUBMENU`, `MNI_CLASS`, `MNI_IS_SUBMENU`, `MNI_POSITION`) VALUES ('reductionplan','angal.menu.btn.reductionplans','angal.menu.reductionplans','x','R','generaldata','org.isf.reductionplan.gui.ReductionPlanBrowser','N',13);
INSERT INTO `oh_groupmenu` (`GM_ID`, `GM_UG_ID_A`, `GM_MNI_ID_A`, `GM_ACTIVE`, `GM_CREATED_BY`, `GM_CREATED_DATE`, `GM_LAST_MODIFIED_BY`, `GM_LAST_MODIFIED_DATE`) VALUES (352,'admin','reductionplan',1,NULL,NULL,NULL,NULL);