CREATE TABLE OH_DEATHREASON(
    DR_ID INT AUTO_INCREMENT,
    DR_CODE VARCHAR(50),
    DR_DESC VARCHAR(255),
    DR_CREATED_BY VARCHAR(50) NOT NULL,
    DR_CREATED_DATE datetime NULL DEFAULT NULL,
    DR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
    DR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
    DR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (DR_ID)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_MORTUARY (
    MRT_ID INT AUTO_INCREMENT,
    MRT_PLACE VARCHAR(100),
    MRT_PAT_ID INT NOT NULL,
    MRT_DR_ID INT NOT NULL,
    MRT_PROVENANCE VARCHAR(100),
    MRT_DEATH_DATE DATETIME NOT NULL,
    MRT_ENTERED_DATE DATETIME NOT NULL,
    MRT_RELEASE_DATE DATETIME NOT NULL,
    MRT_PROVISIONAL_RELEASE_DATE DATETIME NOT NULL,
    MRT_DECLARING_NAME VARCHAR(100) NOT NULL,
   	MRT_DECLARING_PHONE VARCHAR(20),
   	MRT_DECLARING_NEST VARCHAR(20),
   	MRT_LOCKER VARCHAR(20),
    MRT_CREATED_BY VARCHAR(50) NOT NULL,
    MRT_FAMILY_NAME VARCHAR(100),
    MRT_FAMILY_PHONE VARCHAR(20),
    MRT_FAMILY_NEST VARCHAR(20),
    MRT_CREATED_DATE datetime NULL DEFAULT NULL,
    MRT_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
    MRT_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
    MRT_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    MRT_DELETED TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (MRT_ID),
    CONSTRAINT FK_MORTUARY_PAT_ID FOREIGN KEY (MRT_PAT_ID) REFERENCES OH_PATIENT (PAT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_MORTUARY_DR_ID FOREIGN KEY (MRT_DR_ID) REFERENCES OH_DEATHREASON (DR_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_MORTUARY_CREATED_BY FOREIGN KEY (MRT_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_MORTUARY_LAST_MODIFIED_BY FOREIGN KEY (MRT_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

-- Rearrange main menu
UPDATE MENUITEM SET MNI_POSITION=12 WHERE MNI_ID_A="generaldata";
UPDATE MENUITEM SET MNI_POSITION=13 WHERE MNI_ID_A="help";

--Add mortuary in the main menu
INSERT INTO `oh_menuitem` (`MNI_ID_A`, `MNI_BTN_LABEL`, `MNI_LABEL`, `MNI_TOOLTIP`, `MNI_SHORTCUT`, `MNI_SUBMENU`, `MNI_CLASS`, `MNI_IS_SUBMENU`, `MNI_POSITION`) VALUES ('mortuary', 'angal.menu.btn.mortuary', 'angal.menu.mortuary', 'x', 'U', 'main', 'org.isf.mortuary.gui.MortuaryBrowser','N', 11);

INSERT INTO `oh_groupmenu` (`GM_ID`, `GM_UG_ID_A`, `GM_MNI_ID_A`, `GM_ACTIVE`, `GM_CREATED_BY`, `GM_CREATED_DATE`, `GM_LAST_MODIFIED_BY`, `GM_LAST_MODIFIED_DATE`) VALUES (350,'admin','mortuary',1,NULL,NULL,NULL,NULL);