CREATE TABLE OH_MORTUARYSTAYS (
   MRTST_CODE VARCHAR(11) NOT NULL UNIQUE,
   MRTST_NAME VARCHAR(100) NOT NULL,
   MRTST_DESC VARCHAR(255) NOT NULL,
   MRTST_MIN_DAYS INT NOT NULL,
   MRTST_MAX_DAYS INT NOT NULL,
   MRTST_CREATED_BY VARCHAR(50) NOT NULL,
   MRTST_CREATED_DATE datetime NULL DEFAULT NULL,
   MRTST_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
   MRTST_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
   MRTST_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
   PRIMARY KEY (MRTST_CODE)
);

ALTER TABLE OH_MORTUARYSTAYS MODIFY COLUMN MRTST_CREATED_BY VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_uca1400_ai_ci;

ALTER TABLE OH_MORTUARYSTAYS MODIFY COLUMN MRTST_LAST_MODIFIED_BY VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_uca1400_ai_ci;

ALTER TABLE OH_MORTUARYSTAYS ADD CONSTRAINT FK_OH_MORTUARYSTAYS_USER_1 FOREIGN KEY (MRTST_CREATED_BY) REFERENCES OH_USER (US_ID_A);

ALTER TABLE OH_MORTUARYSTAYS ADD CONSTRAINT FK_OH_MORTUARYSTAYS_USER_2 FOREIGN KEY (MRTST_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A);
