CREATE TABLE OH_MORTUARYSTAYS (
   MRTST_CODE VARCHAR(11) NOT NULL UNIQUE,
   MRTST_NAME VARCHAR(100) NOT NULL,
   MRTST_DESC VARCHAR(255) NOT NULL,
   MRTST_MIN_DAYS INT NOT NULL,
   MRTST_MAX_DAYS INT NOT NULL,
   MRTST_CREATED_BY VARCHAR(50) NOT NULL,
   MRTST_CREATED_DATE datetime NULL DEFAULT NULL,
   MRTST_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
   MRTST_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
   MRTST_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
   PRIMARY KEY (MRTST_CODE),
   CONSTRAINT FK_MORTUARYSTAYS_CREATED_BY FOREIGN KEY (MRTST_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT FK_MORTUARYSTAYS_LAST_MODIFIED_BY FOREIGN KEY (MRTST_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
   INDEX FK_MORTUARYSTAYS_CREATED_BY_IDX (MRTST_CREATED_BY ASC)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;