CREATE TABLE OH_MORTUARY (
    MOR_ID VARCHAR(11) NOT NULL,
    MOR_NAME VARCHAR(150) NOT NULL,
    MOR_DMAX INT NOT NULL,
    MOR_DMIN INT NOT NULL,
    MOR_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
    MOR_CREATED_DATE datetime NULL DEFAULT NULL,
    MOR_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
    MOR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
    MOR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (MOR_ID)
);
