
--
-- Definition of table oh_reductionplan
--

CREATE TABLE oh_reductionplan (
  RP_ID INT(11) NOT NULL AUTO_INCREMENT,
  RP_DESCRIPTION VARCHAR(100) NOT NULL,
  RP_OPERATIONRATE FLOAT NOT NULL,
  RP_MEDICALRATE FLOAT NOT NULL,
  RP_EXAMRATE FLOAT NOT NULL,
  RP_OTHERRATE FLOAT NOT NULL,
  RP_LOCK INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (RP_ID),
  RP_CREATED_BY VARCHAR(50) NOT NULL,
  RP_CREATED_DATE datetime NULL DEFAULT NULL,
  RP_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  RP_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  RP_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT FK_REDUCTIONPLAN_CREATED_BY FOREIGN KEY (RP_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_REDUCTIONPLAN_LAST_MODIFIED_BY FOREIGN KEY (RP_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  INDEX FK_REDUCTIONPLAN_CREATED_BY_IDX (RP_CREATED_BY ASC)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;


--
-- Definition of table oh_otherreduction
--

CREATE TABLE oh_otherreduction (
  OTR_RP_ID INT(11) NOT NULL,
  OTR_OTH_ID INT(11) NOT NULL,
  OTR_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (OTR_RP_ID, OTR_OTH_ID)
);

--
-- Definition of table oh_exampsreduction
--

CREATE TABLE oh_examsreduction (
  ER_RP_ID INT(11) NOT NULL,
  ER_EXA_ID_A VARCHAR(10) NOT NULL,
  ER_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (ER_RP_ID, ER_EXA_ID_A)
);


--
-- Definition of table oh_medicalsreduction
--
CREATE TABLE oh_medicalsreduction (
  MR_RP_ID INT(11) NOT NULL,
  MR_MED_ID INT(11) NOT NULL,
  MR_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (MR_RP_ID, MR_MED_ID)
);

--
-- Definition of table oh_operationsreduction
--

CREATE TABLE oh_operationsreduction (
  OPR_RP_ID INT(11) NOT NULL,
  OPR_OPE_ID_A VARCHAR(10) NOT NULL,
  OPR_REDUCTIONRATE FLOAT NOT NULL,
  PRIMARY KEY (OPR_RP_ID, OPR_OPE_ID_A)
);