CREATE TABLE OH_MORTUARYSTAYS (
   MRTST_ID INT AUTO_INCREMENT,
   MRTST_CODE VARCHAR(11) NOT NULL,
   MRTST_NAME VARCHAR(100) NOT NULL,
   MRTST_DESC VARCHAR(255) NOT NULL,
   MRTST_MIN_DAYS INT NOT NULL,
   MRTST_MAX_DAYS INT NOT NULL,
   MRTST_CREATED_BY VARCHAR(50) NOT NULL,
   MRTST_CREATED_DATE datetime NULL DEFAULT NULL,
   MRTST_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
   MRTST_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
   MRTST_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
   MRTST_DELETED TINYINT(1) NOT NULL DEFAULT 0,
   PRIMARY KEY (MRTST_ID),
   CONSTRAINT FK_MORTUARYSTAYS_CREATED_BY FOREIGN KEY (MRTST_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
   CONSTRAINT FK_MORTUARYSTAYS_LAST_MODIFIED_BY FOREIGN KEY (MRTST_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
   INDEX FK_MORTUARYSTAYS_CREATED_BY_IDX (MRTST_CREATED_BY ASC)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

INSERT INTO `oh_menuitem` (`MNI_ID_A`, `MNI_BTN_LABEL`, `MNI_LABEL`, `MNI_TOOLTIP`, `MNI_SHORTCUT`, `MNI_SUBMENU`, `MNI_CLASS`, `MNI_IS_SUBMENU`, `MNI_POSITION`) VALUES ('mortuarystays', 'angal.menu.btn.mortuarystays', 'angal.menu.mortuarystays', 'x', 'U', 'generaldata', 'org.isf.mortuarystays.gui.MortuaryStaysBrowser','N', 11);

INSERT INTO `oh_groupmenu` (`GM_ID`, `GM_UG_ID_A`, `GM_MNI_ID_A`, `GM_ACTIVE`, `GM_CREATED_BY`, `GM_CREATED_DATE`, `GM_LAST_MODIFIED_BY`, `GM_LAST_MODIFIED_DATE`) VALUES (349,'admin','mortuarystays',1,NULL,NULL,NULL,NULL);