CREATE TABLE OH_MORTUARY (
    MOR_ID VARCHAR(11) NOT NULL,
    MOR_NAME VARCHAR(150) NOT NULL,
    MOR_DMAX INT NOT NULL,
    MOR_DMIN INT NOT NULL,
    PRIMARY KEY (MOR_ID)
);




---- Collecting supplier old informations
--INSERT INTO MORTUARY (SUP_NAME) SELECT DISTINCT(MMV_FROM) FROM MEDICALDSRSTOCKMOV WHERE MMV_FROM IS NOT NULL;
--
---- Updating MEDICALDSRSTOCKMOV table with new codes
--UPDATE MEDICALDSRSTOCKMOV JOIN SUPPLIER ON MMV_FROM = SUP_NAME SET MMV_FROM = SUP_ID;
---- UPDATE MEDICALDSRSTOCKMOV SET MMV_FROM = 0 WHERE MMV_FROM IS NULL;
--
---- Altering MEDICALDSRSTOCKMOV table to reflect codes type
--ALTE