
--
-- Definition of table reductionplan
--

CREATE TABLE oh_reductionplan (
    RP_ID INT(11) NOT NULL AUTO_INCREMENT,
    RP_DESCRIPTION VARCHAR(100) NOT NULL,
    RP_OPERATIONRATE FLOAT NOT NULL,
    RP_MEDICALRATE FLOAT NOT NULL,
    RP_EXAMRATE FLOAT NOT NULL,
    RP_OTHERRATE FLOAT NOT NULL,
    RP_DATE DATETIME NOT NULL,
    RP_UPDATE DATETIME NOT NULL,
    PRIMARY KEY (RP_ID)
) ENGINE=MyISAM;
