CREATE TABLE OH_DEATHREASON(
    DTHR_ID INT AUTO_INCREMENT,
    DTHR_CODE VARCHAR(50) NOT NULL UNIQUE,
    DTHR_DESC VARCHAR(255) NOT NULL,
    DTHR_CREATED_BY VARCHAR(50) NOT NULL,
    DTHR_CREATED_DATE datetime NULL DEFAULT NULL,
    DTHR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
    DTHR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
    DTHR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    DTHR_DELETED TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (DTHR_ID)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_DEATH (
    DTH_ID INT AUTO_INCREMENT,
    DTH_PLACE VARCHAR(100),
    DTH_PAT_ID INT NOT NULL,
    DTH_DTHR_ID INT NOT NULL,
    DTH_WRD_ID_A CHAR(3),
    DTH_DATE DATETIME NOT NULL,
    DTH_ADMISSION_DATE DATETIME NOT NULL,
    DTH_DISCHARGE_DATE DATETIME NOT NULL,
    DTH_ESTIMATED_DISCHARGE_DATE DATETIME NOT NULL,
    DTH_DECLARING_NAME VARCHAR(100) NOT NULL,
   	DTH_DECLARING_PHONENUMBER VARCHAR(20),
   	DTH_DECLARING_NID VARCHAR(20),
   	DTH_LOCKER_NUMBER VARCHAR(20),
    DTH_CREATED_BY VARCHAR(50) NOT NULL,
    DTH_FAMILY_NAME VARCHAR(100),
    DTH_FAMILY_PHONENUMBER VARCHAR(20),
    DTH_FAMILY_NID VARCHAR(20),
    DTH_CREATED_DATE datetime NULL DEFAULT NULL,
    DTH_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
    DTH_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
    DTH_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    DTH_DELETED TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (DTH_ID),
    CONSTRAINT FK_DEATH_PAT_ID FOREIGN KEY (DTH_PAT_ID) REFERENCES OH_PATIENT (PAT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_DEATH_WRD_ID_A FOREIGN KEY (DTH_WRD_ID_A) REFERENCES OH_WARD (WRD_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_DEATH_DTHR_ID FOREIGN KEY (DTH_DTHR_ID) REFERENCES OH_DEATHREASON (DTHR_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_DEATH_CREATED_BY FOREIGN KEY (DTH_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_DEATH_LAST_MODIFIED_BY FOREIGN KEY (DTH_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

-- Rearrange main menu
UPDATE OH_MENUITEM SET MNI_POSITION=12 WHERE MNI_ID_A="generaldata";
UPDATE OH_MENUITEM SET MNI_POSITION=13 WHERE MNI_ID_A="help";

--Add mortuary in the main menu
INSERT INTO `oh_menuitem` (`MNI_ID_A`, `MNI_BTN_LABEL`, `MNI_LABEL`, `MNI_TOOLTIP`, `MNI_SHORTCUT`, `MNI_SUBMENU`, `MNI_CLASS`, `MNI_IS_SUBMENU`, `MNI_POSITION`) VALUES ('mortuary', 'angal.menu.btn.mortuary', 'angal.menu.mortuary', 'x', 'U', 'main', 'org.isf.mortuary.gui.MortuaryBrowser','N', 11);

INSERT INTO `oh_groupmenu` (`GM_ID`, `GM_UG_ID_A`, `GM_MNI_ID_A`, `GM_ACTIVE`, `GM_CREATED_BY`, `GM_CREATED_DATE`, `GM_LAST_MODIFIED_BY`, `GM_LAST_MODIFIED_DATE`) VALUES (350,'admin','mortuary',1,NULL,NULL,NULL,NULL);