
ALTER TABLE OH_OPD ADD COLUMN IF NOT EXISTS OPD_REFERRAL_FROM VARCHAR(255);

ALTER TABLE OH_OPD ADD COLUMN IF NOT EXISTS OPD_REFERRAL_TO VARCHAR(255);

UPDATE OH_OPD SET OPD_REFERRAL_FROM = NULL WHERE OPD_REFERRAL_FROM = 'R';
UPDATE OH_OPD SET OPD_REFERRAL_TO = NULL WHERE OPD_REFERRAL_TO = 'R';