BeninRepublic = REPUBLIC OF BENIN

Department = ZOU-COLLINES DEPARTMENTAL HEALTH DIRECTORATE

Hospital = Sokponta-Glazoué Children's Hospital L'ABBRACCIO

ExitPoint = EXIT POINT

FullName = First and last name:

PlaceOfOrigin = Place of origin:

FullNameOfFather = Father's first and last name:

FullNameOfMother = Mother's first and last name:

Phone = Phone number :

InDate = Date and time of admission :

OutDate = Date and time of discharge :

InDiagnosis = Admission diagnosis :

OutDiagnosis = Discharge diagnosis :

OutPutType = Discharge type :

OutPutTreatment = Treatment upon patient discharge :

NextAppointment = Patient's next appointment :

OtherInformation = Other information :

DoctorSignature = Physician's signature