BeninRepublic = REPUBLIC OF BENIN

Department = COLLINES DEPARTMENTAL HEALTH DIRECTORATE

Hospital = Sokponta-Glazoué Children's Hospital L'ABBRACCIO

GeneralPediatricsDepartment = GENERAL PEDIATRICS DEPARTMENT

REPORT_TITLE=Discharge Statistics Report

DISCHARGE_TYPE=Discharge Type

NUMBER=Number

TOTAL=Total

GRAND_TOTAL=Grand Total

REPORT_GENERATED_ON=Report generated on

FROM=From

TO=To

WARD_NAME=Ward
