ALTER TABLE OH_BILLITEMS ADD COLUMN BLI_ITEM_GROUP VARCHAR(3) NULL DEFAULT NULL;
ALTER TABLE OH_BILLITEMS ADD COLUMN BLI_PRESC_ID INT NULL DEFAULT NULL;

ALTER TABLE OH_THERAPIES ADD COLUMN THR_QTY_BOUGTH DOUBLE DEFAULT 0;

ALTER TABLE OH_LABORATORY ADD COLUMN LAB_BLL_ID INT NULL DEFAULT NULL;
