ALTER TABLE OH_EXAM
    ADD COLUMN EXA_AFM_ID INT DEFAULT NULL,
    ADD CONSTRAINT FK_EXAM_ARTICLE_FAMILY
        FOREIGN KEY (EXA_AFM_ID)
        REFERENCES OH_ARTICLE_FAMILIES(AFM_ID);

CREATE INDEX IDX_EXAM_AFM_ID
    ON OH_EXAM(EXA_AFM_ID);


ALTER TABLE OH_OPERATION
    ADD COLUMN OPE_AFM_ID INT DEFAULT NULL,
    ADD CONSTRAINT FK_OPERATION_ARTICLE_FAMILY
        FOREIGN KEY (OPE_AFM_ID)
        REFERENCES OH_ARTICLE_FAMILIES(AFM_ID);

CREATE INDEX IDX_OPERATION_AFM_ID
    ON OH_OPERATION(OPE_AFM_ID);


ALTER TABLE OH_MEDICALDSR
    ADD COLUMN MDSR_AFM_ID INT DEFAULT NULL,
    ADD CONSTRAINT FK_MEDICAL_ARTICLE_FAMILY
        FOREIGN KEY (MDSR_AFM_ID)
        REFERENCES OH_ARTICLE_FAMILIES(AFM_ID);

CREATE INDEX IDX_MEDICALDSR_AFM_ID
    ON OH_MEDICALDSR(MDSR_AFM_ID);


ALTER TABLE OH_PRICESOTHERS
    ADD COLUMN OTH_AFM_ID INT DEFAULT NULL,
    ADD CONSTRAINT FK_PRICESOTHERS_ARTICLE_FAMILY
        FOREIGN KEY (OTH_AFM_ID)
        REFERENCES OH_ARTICLE_FAMILIES(AFM_ID);

CREATE INDEX IDX_PRICESOTHERS_AFM_ID
    ON OH_PRICESOTHERS(OTH_AFM_ID);