CREATE TABLE IF NOT EXISTS `OH_COUNTRY` (
    `CNT_ID` INT NOT NULL AUTO_INCREMENT,
    `CNT_ISO_CODE` VARCHAR(2) NOT NULL,
    `CNT_PHONE_CODE` VARCHAR(10) NOT NULL,
    `CNT_NAME` VARCHAR(100) NOT NULL,
    `CNT_LOCK` INT DEFAULT 0,
    `CNT_CREATED_BY` VARCHAR(50) DEFAULT NULL,
    `CNT_CREATED_DATE` DATETIME DEFAULT NULL,
    `CNT_LAST_MODIFIED_BY` VARCHAR(50) DEFAULT NULL,
    `CNT_LAST_MODIFIED_DATE` DATETIME DEFAULT NULL,
    `CNT_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`CNT_ID`),
    UNIQUE KEY `uk_country_iso_code` (`CNT_ISO_CODE`),
    UNIQUE KEY `uk_country_phone_code` (`CNT_PHONE_CODE`),
    UNIQUE KEY `uk_country_name` (`CNT_NAME`)
    ) ENGINE=InnoDB