ALTER TABLE `oh_patient`
    ADD COLUMN `PAT_BIRTH_PLACE` VARCHAR(100) DEFAULT NULL AFTER `PAT_CITY`,
    ADD COLUMN `PAT_NUMBER_OF_CHILDREN` INT DEFAULT 0 AFTER `PAT_BIRTH_PLACE`,
    ADD COLUMN `PAT_GEOGRAPHIC_POSITION` VARCHAR(30) DEFAULT NULL AFTER `PAT_NUMBER_OF_CHILDREN`,
    ADD COLUMN `PAT_PARENTS_RESIDENCE` VARCHAR(255) DEFAULT NULL AFTER `PAT_GEOGRAPHIC_POSITION`,
    ADD COLUMN `PAT_TRANSPORT_MEANS` VARCHAR(100) DEFAULT NULL AFTER `PAT_PARENTS_RESIDENCE`,
    ADD COLUMN `PAT_COUNTRY_ID` BIGINT DEFAULT NULL AFTER `PAT_TRANSPORT_MEANS`,
    ADD COLUMN `PAT_AFFILIATED_PATIENT_ID` INT DEFAULT NULL AFTER `PAT_COUNTRY_ID`;
    ADD CONSTRAINT `fk_patient_country` FOREIGN KEY (`PAT_COUNTRY_ID`) REFERENCES `OH_COUNTRY`(`CNT_ID`),
