-- Orthanc Config Access And lien Orthanc Patient to patient int OH

-- Create new table Orthanc config user access
CREATE TABLE OH_ORTHANC_CONFIG (
  ORC_ID int(11) NOT NULL AUTO_INCREMENT,
  ORC_USER_NAME VARCHAR(50) NOT NULL,
  ORC_US_ID_A varchar(50) NOT NULL, 
  ORC_PASSWORD VARCHAR(50) NOT NULL,
  ORC_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORC_CREATED_DATE datetime NULL DEFAULT NULL,
  ORC_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORC_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ORC_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (ORC_ID),
  FOREIGN KEY (ORC_US_ID_A) REFERENCES OH_USER(US_ID_A) ON DELETE CASCADE,
  UNIQUE (ORC_US_ID_A)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

-- Create new table for Orthanc patient 

CREATE TABLE OH_ORTHANC_PATIENT (
  ORP_ID int(11) NOT NULL AUTO_INCREMENT,
  ORP_PATIENT_ID VARCHAR(200) NOT NULL,
  ORP_PAT_ID_A int(11) NOT NULL, 
  ORP_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORP_CREATED_DATE datetime NULL DEFAULT NULL,
  ORP_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORP_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ORP_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (ORP_ID),
  FOREIGN KEY (ORP_PAT_ID_A) REFERENCES OH_PATIENT(PAT_ID) ON DELETE CASCADE,
  UNIQUE (ORP_PAT_ID_A)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

INSERT INTO `oh_orthanc_config`(`ORC_ID`, `ORC_USER_NAME`, `ORC_US_ID_A`, `ORC_PASSWORD`, `ORC_CREATED_BY`, `ORC_CREATED_DATE`, `ORC_LAST_MODIFIED_BY`, `ORC_LAST_MODIFIED_DATE`, `ORC_ACTIVE`) VALUES (1,'u2g','laboratorist','u2g123',NULL,NULL,NULL,NULL,1)