CREATE TABLE IF NOT EXISTS OH_ADMISSIONDIAGNOSIS (
    ADMD_ADM_ID INT NOT NULL,
    ADMD_DIS_ID_A VARCHAR(10) NOT NULL,
    ADMD_LOCK INT NOT NULL DEFAULT 0,
    ADMD_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,

    PRIMARY KEY (ADMD_ADM_ID, ADMD_DIS_ID_A),
    INDEX IDX_ADMD_DIS_ID_A (ADMD_DIS_ID_A),

    CONSTRAINT FK_ADMD_ADMISSION FOREIGN KEY (ADMD_ADM_ID) REFERENCES oh_admission(ADM_ID),
    CONSTRAINT FK_ADMD_DISEASE FOREIGN KEY (ADMD_DIS_ID_A) REFERENCES oh_disease(DIS_ID_A)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS OH_ADMISSIONDIAGNOSISOUT (
    ADMDO_ADM_ID INT NOT NULL,
    ADMDO_DIS_ID_A VARCHAR(10) NOT NULL,
    ADMDO_LOCK INT NOT NULL DEFAULT 0,
    ADMDO_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,

    PRIMARY KEY (ADMDO_ADM_ID, ADMDO_DIS_ID_A),
    INDEX IDX_ADMDO_DIS_ID_A (ADMDO_DIS_ID_A),

    CONSTRAINT FK_ADMDO_ADMISSION FOREIGN KEY (ADMDO_ADM_ID) REFERENCES oh_admission(ADM_ID),
    CONSTRAINT FK_ADMDO_DISEASE FOREIGN KEY (ADMDO_DIS_ID_A) REFERENCES oh_disease(DIS_ID_A)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;