--
-- Extended patient demographics and administrative fields ported from oh-mada-gui's
-- PatientInsertExtended: birth place, geographic area, household details, transport, a
-- client-required "Blama" field, a country lookup with an inline create dialog, an
-- employee/head-of-household affiliation link, and a price-list assignment.
--

CREATE TABLE OH_COUNTRY (
	CTR_ID int(11) NOT NULL AUTO_INCREMENT,
	CTR_CODE varchar(20) DEFAULT NULL,
	CTR_NAME varchar(50) NOT NULL,
	CTR_PHONE_CODE varchar(10) DEFAULT NULL,
	CTR_LOCK int(11) NOT NULL DEFAULT 0,
	CTR_CREATED_BY varchar(50) DEFAULT NULL,
	CTR_CREATED_DATE datetime DEFAULT NULL,
	CTR_LAST_MODIFIED_BY varchar(50) DEFAULT NULL,
	CTR_LAST_MODIFIED_DATE datetime DEFAULT NULL,
	CTR_ACTIVE tinyint(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (CTR_ID)
) ENGINE=InnoDB;

ALTER TABLE OH_PATIENT ADD COLUMN PAT_BIRTH_PLACE varchar(100) DEFAULT NULL AFTER PAT_PROFESSION;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_GEOGRAPHIC_AREA varchar(30) DEFAULT NULL AFTER PAT_BIRTH_PLACE;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_CHILDREN_NUMBER int(11) DEFAULT 0 AFTER PAT_GEOGRAPHIC_AREA;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_PARENT_RESIDENCE varchar(50) DEFAULT NULL AFTER PAT_CHILDREN_NUMBER;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_TRANSPORT varchar(254) DEFAULT NULL AFTER PAT_PARENT_RESIDENCE;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_BLAMA varchar(40) DEFAULT NULL AFTER PAT_TRANSPORT;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_COUNTRY varchar(30) DEFAULT NULL AFTER PAT_BLAMA;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_AFFILIATED_PERSON int(11) DEFAULT NULL AFTER PAT_COUNTRY;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_IS_HEAD_AFFILIATION tinyint(1) NOT NULL DEFAULT 0 AFTER PAT_AFFILIATED_PERSON;
ALTER TABLE OH_PATIENT ADD COLUMN PAT_LST_ID int(11) DEFAULT NULL AFTER PAT_IS_HEAD_AFFILIATION;
