-- ============================================================
--  CPN module (Consultation Prénatale) — Phase 2/5
--  Tables: OH_PREGNANCYDELIVERY, OH_PREGNANCYNEWBORN (1 to 4 children
--          per delivery, replaces the old fixed newborn1..3 UI columns)
-- ============================================================

CREATE TABLE IF NOT EXISTS OH_PREGNANCYDELIVERY (
    PDEL_ID                     INT AUTO_INCREMENT PRIMARY KEY,
    PDEL_ADM_ID                 INT          DEFAULT NULL,
    PDEL_PREG_ID                INT          DEFAULT NULL,
    PDEL_DATE_DEL                DATETIME     DEFAULT NULL,
    PDEL_FATHER_NAME             VARCHAR(100) DEFAULT NULL,
    PDEL_FATHER_OCCUPATION       VARCHAR(100) DEFAULT NULL,
    PDEL_FATHER_RESIDENCE        VARCHAR(100) DEFAULT NULL,
    PDEL_FATHER_BIRTH_PLACE      VARCHAR(100) DEFAULT NULL,
    PDEL_FATHER_AGE              INT          DEFAULT NULL,
    PDEL_FATHER_CNI              BIGINT       DEFAULT NULL,
    PDEL_LOCHIES                 VARCHAR(10)  DEFAULT NULL,
    PDEL_COUNSELING              VARCHAR(255) DEFAULT NULL,
    PDEL_FP_METHOD               VARCHAR(100) DEFAULT NULL,
    PDEL_CREATED_BY              VARCHAR(50)  DEFAULT NULL,
    PDEL_CREATED_DATE            DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PDEL_LAST_MODIFIED_BY        VARCHAR(50)  DEFAULT NULL,
    PDEL_LAST_MODIFIED_DATE      DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PDEL_ACTIVE                   TINYINT(1)   NOT NULL DEFAULT 1,

    CONSTRAINT FK_PREGNANCYDELIVERY_ADMISSION FOREIGN KEY (PDEL_ADM_ID) REFERENCES OH_ADMISSION(ADM_ID),
    CONSTRAINT FK_PREGNANCYDELIVERY_PREGNANCY FOREIGN KEY (PDEL_PREG_ID) REFERENCES OH_PREGNANCY(PREG_ID),
    INDEX IDX_PDEL_ADM_ID (PDEL_ADM_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS OH_PREGNANCYNEWBORN (
    PNB_ID                       INT AUTO_INCREMENT PRIMARY KEY,
    PNB_PDEL_ID                  INT          NOT NULL,
    PNB_CHILD_NUMBER             TINYINT      NOT NULL DEFAULT 1,
    PNB_CHILD_NAME                VARCHAR(100) DEFAULT NULL,
    PNB_SEX                      CHAR(1)      NOT NULL DEFAULT 'F',
    PNB_DLT_ID_A                 CHAR(1)      DEFAULT NULL,
    PNB_DRT_ID_A                 CHAR(1)      DEFAULT NULL,
    PNB_WEIGHT                   FLOAT        DEFAULT NULL COMMENT 'grams',
    PNB_HEIGHT                   FLOAT        DEFAULT NULL COMMENT 'cm',
    PNB_HEAD_CIRC                 DOUBLE       DEFAULT NULL COMMENT 'PC, max 100 cm',
    PNB_CHEST_CIRC                DOUBLE       DEFAULT NULL COMMENT 'PT, max 50 cm',
    PNB_ARM_CIRC                  DOUBLE       DEFAULT NULL COMMENT 'PB, max 30 cm',
    PNB_COMPLICATIONS             VARCHAR(255) DEFAULT NULL COMMENT 'registre colonne 31',
    PNB_MALFORMATION              VARCHAR(255) DEFAULT NULL COMMENT 'registre colonne 32',
    PNB_FEEDING_MODE              VARCHAR(30)  DEFAULT NULL COMMENT 'registre colonne 33',
    PNB_HIV_EXPOSED               TINYINT(1)   NOT NULL DEFAULT 0,
    PNB_CREATED_BY                VARCHAR(50)  DEFAULT NULL,
    PNB_CREATED_DATE              DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PNB_LAST_MODIFIED_BY          VARCHAR(50)  DEFAULT NULL,
    PNB_LAST_MODIFIED_DATE        DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PNB_ACTIVE                     TINYINT(1)   NOT NULL DEFAULT 1,

    CONSTRAINT FK_PREGNANCYNEWBORN_DELIVERY FOREIGN KEY (PNB_PDEL_ID) REFERENCES OH_PREGNANCYDELIVERY(PDEL_ID),
    CONSTRAINT FK_PREGNANCYNEWBORN_DELIVERYTYPE FOREIGN KEY (PNB_DLT_ID_A) REFERENCES OH_DELIVERYTYPE(DLT_ID_A),
    CONSTRAINT FK_PREGNANCYNEWBORN_DELIVERYRESULTTYPE FOREIGN KEY (PNB_DRT_ID_A) REFERENCES OH_DELIVERYRESULTTYPE(DRT_ID_A),
    INDEX IDX_PNB_PDEL_ID (PNB_PDEL_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;
