CREATE TABLE OH_BODYCOMPARTMENT(
    BC_ID INT AUTO_INCREMENT,
    BC_LABEL VARCHAR(6) NOT NULL,
    BC_DESC VARCHAR(255) NULL DEFAULT NULL,
    BC_CREATED_BY VARCHAR(50) NOT NULL,
    BC_CREATED_DATE datetime NULL DEFAULT NULL,
    BC_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
    BC_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
    BC_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    BC_DELETED TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (BC_ID)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;