-- ========================================================================
-- Tuberculosis Follow-up Module - Complete database setup
-- ========================================================================
-- This script creates all tables for the TB follow-up module:
--   1. OH_TB_TREATMENT    - TB treatment enrollment records
--   2. OH_TB_VISIT        - Follow-up visits
--   3. OH_TB_CONTACT      - Contact tracing
--   4. Typologies         - TB regimen types and contact relationships
-- ========================================================================

-- ========================================================================
-- 1. Table: OH_TB_TREATMENT
--    Main table storing TB treatment enrollment per patient episode
--    Links to OH_PATIENT (one patient can have multiple TB episodes)
-- ========================================================================

CREATE TABLE IF NOT EXISTS OH_TB_TREATMENT (
    TBT_ID INT NOT NULL AUTO_INCREMENT,
    TBT_PAT_ID INT NOT NULL,

    TBT_REG_DATE DATETIME NOT NULL,
    TBT_CLASSIFICATION VARCHAR(20) NOT NULL,
    TBT_DISEASE_LOCATION VARCHAR(20) NOT NULL,
    TBT_DISEASE_LOCATION_DETAILS VARCHAR(255) DEFAULT NULL,
    TBT_DIAGNOSIS_DATE DATE DEFAULT NULL,

    TBT_SMEAR_RESULT VARCHAR(20) DEFAULT NULL,
    TBT_GENEXPERT_RESULT VARCHAR(20) DEFAULT NULL,
    TBT_GENEXPERT_RIF_RESISTANCE VARCHAR(20) DEFAULT NULL,
    TBT_CULTURE_RESULT VARCHAR(20) DEFAULT NULL,
    TBT_DST_RESULT VARCHAR(20) DEFAULT NULL,

    TBT_REGIMEN_CODE VARCHAR(20) DEFAULT NULL,
    TBT_TREATMENT_START_DATE DATE NOT NULL,
    TBT_TREATMENT_END_DATE DATE DEFAULT NULL,

    TBT_HIV_STATUS VARCHAR(20) DEFAULT NULL,
    TBT_HIV_TEST_DATE DATE DEFAULT NULL,
    TBT_DIABETES TINYINT(1) DEFAULT 0,
    TBT_KNOWN_CONTACT TINYINT(1) DEFAULT 0,

    TBT_STATUS VARCHAR(20) NOT NULL,
    TBT_OUTCOME VARCHAR(20) DEFAULT NULL,
    TBT_OUTCOME_DATE DATE DEFAULT NULL,

    TBT_NOTES TEXT DEFAULT NULL,

    TBT_LOCK INT DEFAULT 0,

    TBT_CREATED_BY VARCHAR(50) NOT NULL,
    TBT_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TBT_LAST_MODIFIED_BY VARCHAR(50) DEFAULT NULL,
    TBT_LAST_MODIFIED_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    TBT_ACTIVE TINYINT(1) DEFAULT 1,

    PRIMARY KEY (TBT_ID),

    CONSTRAINT FK_TB_TREATMENT_PATIENT
        FOREIGN KEY (TBT_PAT_ID)
        REFERENCES OH_PATIENT(PAT_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    INDEX idx_tb_treatment_pat (TBT_PAT_ID),
    INDEX idx_tb_treatment_status (TBT_STATUS),
    INDEX idx_tb_treatment_reg_date (TBT_REG_DATE),
    INDEX idx_tb_treatment_start_date (TBT_TREATMENT_START_DATE)

) ENGINE = InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS OH_TB_VISIT (
    TBV_ID INT NOT NULL AUTO_INCREMENT,
    TBV_TBT_ID INT NOT NULL,

    TBV_VISIT_DATE DATETIME NOT NULL,

    TBV_WEIGHT DOUBLE DEFAULT NULL,
    TBV_TEMPERATURE DOUBLE DEFAULT NULL,
    TBV_SYMPTOMS_IMPROVED TINYINT(1) DEFAULT NULL,
    TBV_ADHERENCE INT DEFAULT NULL,
    TBV_DOT_STATUS VARCHAR(20) DEFAULT NULL,
    TBV_SIDE_EFFECTS TEXT DEFAULT NULL,

    TBV_SMEAR_RESULT VARCHAR(20) DEFAULT NULL,
    TBV_CULTURE_RESULT VARCHAR(20) DEFAULT NULL,
    TBV_CONVERSION_DATE DATE DEFAULT NULL,
    TBV_CHEST_XRAY_FINDINGS VARCHAR(255) DEFAULT NULL,

    TBV_ALT DOUBLE DEFAULT NULL,
    TBV_AST DOUBLE DEFAULT NULL,
    TBV_CREATININE DOUBLE DEFAULT NULL,
    TBV_HEMOGLOBIN DOUBLE DEFAULT NULL,
    TBV_PLATELETS INT DEFAULT NULL,

    TBV_NEXT_APPOINTMENT_DATE DATE DEFAULT NULL,
    TBV_NOTES TEXT DEFAULT NULL,

    TBV_LOCK INT DEFAULT 0,

    TBV_CREATED_BY VARCHAR(50) NOT NULL,
    TBV_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TBV_LAST_MODIFIED_BY VARCHAR(50) DEFAULT NULL,
    TBV_LAST_MODIFIED_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    TBV_ACTIVE TINYINT(1) DEFAULT 1,

    PRIMARY KEY (TBV_ID),

    CONSTRAINT FK_TB_VISIT_TREATMENT
        FOREIGN KEY (TBV_TBT_ID)
        REFERENCES OH_TB_TREATMENT(TBT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    INDEX idx_tb_visit_treatment (TBV_TBT_ID),
    INDEX idx_tb_visit_date (TBV_VISIT_DATE)

) ENGINE = InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS OH_TB_CONTACT (
    TBC_ID INT NOT NULL AUTO_INCREMENT,
    TBC_TBT_ID INT NOT NULL,

    TBC_NAME VARCHAR(100) NOT NULL,
    TBC_AGE INT DEFAULT NULL,
    TBC_GENDER CHAR(1) DEFAULT NULL,
    TBC_RELATIONSHIP VARCHAR(50) DEFAULT NULL,
    TBC_SCREENED TINYINT(1) DEFAULT 0,
    TBC_SCREENING_DATE DATE DEFAULT NULL,
    TBC_TB_INFECTED TINYINT(1) DEFAULT 0,
    TBC_TB_DISEASE TINYINT(1) DEFAULT 0,
    TBC_TPT_STARTED TINYINT(1) DEFAULT 0,
    TBC_NOTES TEXT DEFAULT NULL,

    TBC_LOCK INT DEFAULT 0,

    TBC_CREATED_BY VARCHAR(50) NOT NULL,
    TBC_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TBC_LAST_MODIFIED_BY VARCHAR(50) DEFAULT NULL,
    TBC_LAST_MODIFIED_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    TBC_ACTIVE TINYINT(1) DEFAULT 1,

    PRIMARY KEY (TBC_ID),

    CONSTRAINT FK_TB_CONTACT_TREATMENT
        FOREIGN KEY (TBC_TBT_ID)
        REFERENCES OH_TB_TREATMENT(TBT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    INDEX idx_tb_contact_treatment (TBC_TBT_ID)

) ENGINE = InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_REGIMEN_NEW_DS', 'Category I - New DS-TB (2HRZE/4HR)', 'TUBERCULOSISREGIMEN', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_REGIMEN_NEW_DS');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_REGIMEN_RETRT_DS', 'Category II - Retreatment DS-TB (2HRZES/1HRZE/5HRE)', 'TUBERCULOSISREGIMEN', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_REGIMEN_RETRT_DS');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_REGIMEN_MDR_SHORT', 'MDR-TB Short regimen (9-12 months)', 'TUBERCULOSISREGIMEN', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_REGIMEN_MDR_SHORT');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_REGIMEN_MDR_LONG', 'MDR-TB Long regimen (18-24 months)', 'TUBERCULOSISREGIMEN', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_REGIMEN_MDR_LONG');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_REGIMEN_XDR', 'XDR-TB regimen', 'TUBERCULOSISREGIMEN', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_REGIMEN_XDR');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_REGIMEN_LTBI', 'LTBI Preventive Treatment', 'TUBERCULOSISREGIMEN', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_REGIMEN_LTBI');

-- TB contact relationship types
INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_CONTACT_HOUSEHOLD', 'Household contact', 'TUBERCULOSISCONTACT', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_CONTACT_HOUSEHOLD');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_CONTACT_FAMILY', 'Family member', 'TUBERCULOSISCONTACT', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_CONTACT_FAMILY');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_CONTACT_FRIEND', 'Friend / Acquaintance', 'TUBERCULOSISCONTACT', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_CONTACT_FRIEND');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_CONTACT_COWORKER', 'Co-worker', 'TUBERCULOSISCONTACT', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_CONTACT_COWORKER');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'TB_CONTACT_HEALTHWRK', 'Healthcare worker', 'TUBERCULOSISCONTACT', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'TB_CONTACT_HEALTHWRK');
