ALTER TABLE OH_CONDITIONING
MODIFY COLUMN COND_VENTILATION BOOLEAN;

ALTER TABLE OH_CONDITIONING
MODIFY COLUMN COND_SNG_NUMBER BOOLEAN;

ALTER TABLE OH_CONDITIONING
ADD COLUMN COND_REHEATING BOOLEAN;

ALTER TABLE OH_CONDITIONING
ADD COLUMN COND_OTHERS_RAPID_TEST VARCHAR(255) DEFAULT NULL;

ALTER TABLE OH_CONDITIONING
ADD COLUMN COND_CPAP_DETAILS TEXT DEFAULT NULL;

ALTER TABLE OH_CONDITIONING
MODIFY COLUMN COND_MCE BOOLEAN;