-- =============================================
-- Table: OH_HOME_VISIT
-- Description: Home visits tracking for patients
-- =============================================

CREATE TABLE IF NOT EXISTS OH_HOME_VISIT (
    HV_ID                       INT AUTO_INCREMENT PRIMARY KEY,
    HV_PAT_ID                   INT          NOT NULL,
    HV_STAFF_ID                 INT          DEFAULT NULL,
    HV_VISIT_START_DATE         DATETIME     NOT NULL,
    HV_VISIT_END_DATE           DATETIME     DEFAULT NULL,
    HV_STATUS                   VARCHAR(20)  NOT NULL DEFAULT 'PLANNED',
    HV_PURPOSE                  VARCHAR(255) DEFAULT NULL,
    HV_CLINICAL_NOTES           TEXT         DEFAULT NULL,
    HV_OBSERVATIONS             TEXT         DEFAULT NULL,
    HV_ADDRESS                  VARCHAR(255) DEFAULT NULL,
    HV_CONTACT_PHONE            VARCHAR(50)  DEFAULT NULL,
    HV_NEXT_VISIT_DATE          DATETIME     DEFAULT NULL,
    HV_CREATED_BY               VARCHAR(50)  DEFAULT NULL,
    HV_CREATED_DATE             DATETIME     DEFAULT NULL,
    HV_LAST_MODIFIED_BY         VARCHAR(50)  DEFAULT NULL,
    HV_LAST_MODIFIED_DATE       DATETIME     DEFAULT NULL,
    HV_ACTIVE                   TINYINT(1)   NOT NULL DEFAULT 1,
    HV_LOCK                     INT          DEFAULT 0,
    FOREIGN KEY (HV_PAT_ID) REFERENCES OH_PATIENT(PAT_ID),
    FOREIGN KEY (HV_STAFF_ID) REFERENCES OH_STAFF(STF_ID),
    KEY IDX_HOME_VISIT_PATIENT (HV_PAT_ID),
    KEY IDX_HOME_VISIT_STAFF (HV_STAFF_ID),
    KEY IDX_HOME_VISIT_START_DATE (HV_VISIT_START_DATE),
    KEY IDX_HOME_VISIT_STATUS (HV_STATUS),
    KEY IDX_HOME_VISIT_NEXT_DATE (HV_NEXT_VISIT_DATE)
    ) ENGINE=InnoDB;