-- Drop the existing table
DROP TABLE IF EXISTS OH_PREGNANCYVISITTYPE;

-- Create Visit Type table (ExamType style)
CREATE TABLE OH_PREGNANCYVISITTYPE (
    PVT_CODE VARCHAR(20) PRIMARY KEY,
    PVT_DESCRIPTION VARCHAR(255) NOT NULL,

    -- Audit fields
    PVT_CREATED_BY VARCHAR(50) NOT NULL,
    PVT_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PVT_LAST_MODIFIED_BY VARCHAR(50),
    PVT_LAST_MODIFIED_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PVT_ACTIVE BOOLEAN DEFAULT TRUE
) ENGINE=INNODB;