 create table dicom (           
	dm_pat_id intEGER not null,
	dm_data longblob, 
	dm_file_id bigint not null auto_increment, 
	dm_file_nome varchar(255) not null,  
	dm_file_accession_number varchar(255),  
	dm_file_institution_name varchar(255),  
	dm_file_pat_uid varchar(255),  
	dm_file_pat_name varchar(255),  
	dm_file_pat_addr varchar(255),  
	dm_file_pat_age varchar(255),  
	dm_file_pat_sex varchar(255),  
	dm_file_pat_birthdate varchar(255),    
	dm_file_st_uid varchar(255) not null,  
	dm_file_st_date varchar(255),  
	dm_file_st_descr varchar(255),   
	dm_file_ser_uid varchar(255) not null,  
	dm_file_ser_inst_uid varchar(255) not null,  
	dm_file_ser_number varchar(255),  
	dm_file_ser_desc_cod_seq varchar(255),  
	dm_file_ser_date varchar(255),  
	dm_file_ser_desc varchar(255),  
	dm_file_inst_uid varchar(255) not null,
	dm_file_modaliity varchar(255),
	dm_thumbnail blob, 
	primary key ( dm_file_id ) 
);