DROP TABLE IF EXISTS OH_ARCHIVED_BILLPAYMENTS;
DROP TABLE IF EXISTS OH_ARCHIVED_BILLITEMS;
DROP TABLE IF EXISTS OH_ARCHIVED_BILLS;
DROP TABLE IF EXISTS OH_PARAMETERS;

CREATE TABLE OH_ARCHIVED_BILLS (
    BLL_ID int(11) NOT NULL AUTO_INCREMENT,
    BLL_DATE datetime NOT NULL,
    BLL_UPDATE datetime NOT NULL,
    BLL_IS_LST tinyint(1) NOT NULL,
    BLL_ID_LST int(11) DEFAULT NULL,
    BLL_LST_NAME varchar(50) DEFAULT NULL,
    BLL_IS_PAT tinyint(1) NOT NULL,
    BLL_ID_PAT int(11) DEFAULT NULL,
    BLL_PAT_NAME varchar(100) DEFAULT NULL,
    BLL_STATUS varchar(1) DEFAULT NULL,
    BLL_AMOUNT double DEFAULT NULL,
    BLL_BALANCE double DEFAULT NULL,
    BLL_USR_ID_A varchar(50) NOT NULL DEFAULT 'admin',
    BLL_ADM_ID int(11) DEFAULT NULL,
    BLL_GUARANTOR varchar(50) DEFAULT NULL,
    BLL_CREATED_BY varchar(50) DEFAULT NULL,
    BLL_CREATED_DATE datetime DEFAULT NULL,
    BLL_LAST_MODIFIED_BY varchar(50) DEFAULT NULL,
    BLL_LAST_MODIFIED_DATE datetime DEFAULT NULL,
    BLL_ACTIVE tinyint(1) NOT NULL DEFAULT 1,
    BLL_LOCK int(11) NOT NULL DEFAULT 0,
    BLL_PARENT_ID int(11) DEFAULT NULL,    -- Ajouté
    BLL_GARANTE varchar(100) DEFAULT NULL,   -- Ajouté
    BLL_IS_CLOSED_MANUALLY tinyint(1) DEFAULT 0, -- Ajouté
    BLL_RP_ID int(11) DEFAULT NULL,
    BLL_WARD_ID varchar(10) DEFAULT NULL,
    PRIMARY KEY (BLL_ID)
) ENGINE=InnoDB;

CREATE TABLE OH_ARCHIVED_BILLITEMS (
    BLI_ID int(11) NOT NULL AUTO_INCREMENT,
    BLI_ID_BILL int(11) DEFAULT NULL,
    BLI_IS_PRICE tinyint(1) NOT NULL,
    BLI_ID_PRICE varchar(28) DEFAULT NULL,
    BLI_ITEM_DESC varchar(100) DEFAULT NULL,
    BLI_ITEM_AMOUNT double NOT NULL,
    BLI_QTY int(11) NOT NULL,
    BLI_ITEM_ID varchar(50) DEFAULT NULL,
    BLI_ITEM_GROUP varchar(3) DEFAULT NULL,
    BLI_PRESC_ID int(11) DEFAULT NULL,
    BLI_CREATED_BY varchar(50) DEFAULT NULL,
    BLI_CREATED_DATE datetime DEFAULT NULL,
    BLI_LAST_MODIFIED_BY varchar(50) DEFAULT NULL,
    BLI_LAST_MODIFIED_DATE datetime DEFAULT NULL,
    BLI_ACTIVE tinyint(1) NOT NULL DEFAULT 1,
    BLI_DATE datetime DEFAULT current_timestamp(), -- Réintroduit pour s'aligner sur la source
    BLI_ITEM_AMOUNT_BRUT double DEFAULT 0,
    PRIMARY KEY (BLI_ID),
    CONSTRAINT FK_ARCHIVED_BILLITEMS_BILL FOREIGN KEY (BLI_ID_BILL)
       REFERENCES OH_ARCHIVED_BILLS (BLL_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE OH_ARCHIVED_BILLPAYMENTS (
    BLP_ID int(11) NOT NULL AUTO_INCREMENT,
    BLP_ID_BILL int(11) DEFAULT NULL,
    BLP_DATE datetime NOT NULL,
    BLP_AMOUNT double NOT NULL,
    BLP_USR_ID_A varchar(50) NOT NULL DEFAULT 'admin',
    BLP_CREATED_BY varchar(50) DEFAULT NULL,
    BLP_CREATED_DATE datetime DEFAULT NULL,
    BLP_LAST_MODIFIED_BY varchar(50) DEFAULT NULL,
    BLP_LAST_MODIFIED_DATE datetime DEFAULT NULL,
    BLP_ACTIVE tinyint(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (BLP_ID),
    CONSTRAINT FK_ARCHIVED_BILLPAYMENTS_BILL FOREIGN KEY (BLP_ID_BILL)
      REFERENCES OH_ARCHIVED_BILLS (BLL_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS OH_PARAMETERS (
    PRMS_ID INT NOT NULL AUTO_INCREMENT,
    PRMS_CODE VARCHAR(50) NOT NULL,
    PRMS_VALUE VARCHAR(70) DEFAULT NULL,
    PRMS_DEFAULT_VALUE VARCHAR(70) NOT NULL,
    PRMS_DESCRIPTION VARCHAR(100) DEFAULT NULL,
    PRMS_CREATE_BY VARCHAR(50) DEFAULT NULL,
    PRMS_MODIFY_BY VARCHAR(50) DEFAULT NULL,
    PRMS_DELETED_BY VARCHAR(50) DEFAULT NULL,
    PRMS_DELETED VARCHAR(1) DEFAULT NULL,
    PRMS_CREATE_DATE DATETIME DEFAULT NULL,
    PRMS_MODIFY_DATE DATETIME DEFAULT NULL,
    PRMS_DELETED_DATE DATETIME DEFAULT NULL,
    PRIMARY KEY (PRMS_ID),
    UNIQUE KEY PRMS_CODE (PRMS_CODE)
    ) ENGINE=InnoDB;

INSERT INTO OH_MENUITEM (
    MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT,
    MNI_SUBMENU,MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION )
VALUES (
   'btnbillarchive', 'angal.billbrowser.archive.btn',
   'angal.billbrowser.archive.btn', 'x', 'A',
   'billsmanager', 'none', 'A', 5
);

INSERT INTO oh_groupmenu (
    GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE, GM_CREATED_BY, GM_CREATED_DATE, GM_LAST_MODIFIED_BY, GM_LAST_MODIFIED_DATE
) SELECT
    'admin', 'btnbillreport', 1, NULL, NULL, NULL,NULL
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM oh_groupmenu
    WHERE GM_UG_ID_A = 'admin'
      AND GM_MNI_ID_A = 'btnbillreport'
);