ALTER TABLE OH_BILLS ADD COLUMN BLL_WRD_ID_A CHAR(3) NULL DEFAULT NULL;
ALTER TABLE OH_BILLS ADD CONSTRAINT FK_OH_BILLS_WARD
	FOREIGN KEY (BLL_WRD_ID_A)
	REFERENCES OH_WARD (WRD_ID_A)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD ADD COLUMN MMVN_BLL_ID INT NULL DEFAULT NULL;
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD ADD CONSTRAINT FK_MEDICALDSRSTOCKMOVWARD_BILL
	FOREIGN KEY (MMVN_BLL_ID)
	REFERENCES OH_BILLS (BLL_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;
