source step_a122_alter_patient_add_new_fields.sql;
source step_a123_menuitem_add_country_menu.sql;
source step_a124_alter_table_opd_add_new_fields.sql;
source step_a132_alter_table_laboratory.sql;
source step_a140_add_reduction_plan_and_price_list_to_patients.sql;
source step_a141_add_column_reduction_plan_id_and_ward_id_to_table_oh_bills.sql;
source step_a143_add_column_medicaldsr.sql;
source step_a163_alter_table_exam_med_operation_add_articlefamiliy.sql;
