CREATE TABLE IF NOT EXISTS OH_COMPLICATIONDIAGNOSIS (
  CD_ADM_ID INT NOT NULL,
  CD_DIS_ID_A VARCHAR(10) NOT NULL,
  CD_LOCK INT NOT NULL DEFAULT 0,
  CD_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  CD_CREATED_BY VARCHAR(50),
  CD_CREATED_DATE DATETIME,
  CD_LAST_MODIFIED_BY VARCHAR(50),
  CD_LAST_MODIFIED_DATE DATETIME,

  PRIMARY KEY (CD_ADM_ID, CD_DIS_ID_A),

  CONSTRAINT FK_COMP_ADMISSION
    FOREIGN KEY (CD_ADM_ID)
    REFERENCES OH_ADMISSION (ADM_ID),

  CONSTRAINT FK_COMP_DISEASE
    FOREIGN KEY (CD_DIS_ID_A)
    REFERENCES OH_DISEASE (DIS_ID_A)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;