-- ============================================================
--  Prescription / billing columns
--  (idempotent: uses conditional PREPARE/EXECUTE blocks, valid on
--   plain MySQL where `ADD COLUMN IF NOT EXISTS` is not supported)
-- ============================================================

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_BILLITEMS' AND COLUMN_NAME = 'BLI_ITEM_GROUP') = 0,
    'ALTER TABLE OH_BILLITEMS ADD COLUMN BLI_ITEM_GROUP VARCHAR(3) NULL DEFAULT NULL',
    'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_BILLITEMS' AND COLUMN_NAME = 'BLI_PRESC_ID') = 0,
    'ALTER TABLE OH_BILLITEMS ADD COLUMN BLI_PRESC_ID INT NULL DEFAULT NULL',
    'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_THERAPIES' AND COLUMN_NAME = 'THR_QTY_BOUGTH') = 0,
    'ALTER TABLE OH_THERAPIES ADD COLUMN THR_QTY_BOUGTH DOUBLE DEFAULT 0',
    'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- LAB_BLL_ID is normally added by step_a121; guard against databases
-- provisioned before that script existed (column referenced by Laboratory.java)
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_LABORATORY' AND COLUMN_NAME = 'LAB_BLL_ID') = 0,
    'ALTER TABLE OH_LABORATORY ADD COLUMN LAB_BLL_ID INT(11) NULL DEFAULT NULL AFTER LAB_PRESCRIBER',
    'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
