ALTER TABLE OH_PATIENT 
ADD COLUMN PAT_COMMUNE VARCHAR(50) NULL DEFAULT '',
ADD COLUMN PAT_ETHNIC VARCHAR(50) NULL DEFAULT '',
ADD COLUMN PAT_FATH_OCCUPATION VARCHAR(50) NULL DEFAULT '',
ADD COLUMN PAT_FATH_AGE INT NULL,
ADD COLUMN PAT_FATH_PHONE VARCHAR(50) NULL DEFAULT '',
ADD COLUMN PAT_MOTH_OCCUPATION VARCHAR(50) NULL DEFAULT '',
ADD COLUMN PAT_MOTH_AGE INT NULL,
ADD COLUMN PAT_MOTH_PHONE VARCHAR(50) NULL DEFAULT ''
;
