CREATE TABLE IF NOT EXISTS OH_INDIAGNOSIS (
  ID_ADM_ID INT NOT NULL,
  ID_DIS_ID_A VARCHAR(10) NOT NULL,
  ID_LOCK INT NOT NULL DEFAULT 0,
  ID_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  ID_CREATED_BY VARCHAR(50),
  ID_CREATED_DATE DATETIME,
  ID_LAST_MODIFIED_BY VARCHAR(50),
  ID_LAST_MODIFIED_DATE DATETIME,

  PRIMARY KEY (ID_ADM_ID, ID_DIS_ID_A),

  CONSTRAINT FK_IN_ADMISSION
    FOREIGN KEY (ID_ADM_ID)
    REFERENCES OH_ADMISSION (ADM_ID),

  CONSTRAINT FK_IN_DISEASE
    FOREIGN KEY (ID_DIS_ID_A)
    REFERENCES OH_DISEASE (DIS_ID_A)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;