CREATE TABLE OH_PARTNERS (
  PRT_ID INT(11) NOT NULL AUTO_INCREMENT,
  PRT_NAME VARCHAR(100) NOT NULL,
  PRT_TYPE VARCHAR(20) NOT NULL,
  PRT_CONTACT_PERSON VARCHAR(100) NULL DEFAULT NULL,
  PRT_PHONE VARCHAR(50) NULL DEFAULT NULL,
  PRT_EMAIL VARCHAR(100) NULL DEFAULT NULL,
  PRT_ADDRESS VARCHAR(255) NULL DEFAULT NULL,
  PRT_NOTES TEXT NULL,
  PRT_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
  PRT_CREATED_DATE DATETIME NULL DEFAULT NULL,
  PRT_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  PRT_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  PRT_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRT_LOCK INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (PRT_ID),
  KEY IDX_PARTNER_NAME (PRT_NAME),
  CONSTRAINT FK_PARTNERS_TYPE FOREIGN KEY (PRT_TYPE) REFERENCES OH_PARTNERTYPES (PRTT_CODE)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_PATIENT_PARTNERS (
  PP_PAT_ID INT(11) NOT NULL,
  PP_PRT_ID INT(11) NOT NULL,
  PRIMARY KEY (PP_PAT_ID, PP_PRT_ID),
  CONSTRAINT FK_PATIENT_PARTNERS_PAT_ID FOREIGN KEY (PP_PAT_ID) REFERENCES OH_PATIENT (PAT_ID),
  CONSTRAINT FK_PATIENT_PARTNERS_PRT_ID FOREIGN KEY (PP_PRT_ID) REFERENCES OH_PARTNERS (PRT_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

INSERT INTO OH_MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION) VALUES ('partners','angal.menu.btn.partners','angal.menu.partners','x','P','generaldata','org.isf.partner.gui.PartnerBrowser','N',12);
INSERT INTO OH_GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','partners',1);
