ALTER TABLE `OH_PREGNANCY`
    ADD COLUMN IF NOT EXISTS `PRG_TERM_DELIVERIES` INT(11) DEFAULT 0 COMMENT 'Number of term deliveries (≥ 37 weeks)' AFTER `PRG_MISSCARRIAGES`,
    ADD COLUMN IF NOT EXISTS `PRG_PRETERM_DELIVERIES` INT(11) DEFAULT 0 COMMENT 'Number of preterm deliveries (< 37 weeks)' AFTER `PRG_TERM_DELIVERIES`,
    ADD COLUMN IF NOT EXISTS `PRG_LIVING_CHILDREN` INT(11) DEFAULT 0 COMMENT 'Number of living children' AFTER `PRG_PRETERM_DELIVERIES`,
    ADD COLUMN IF NOT EXISTS `PRG_STILLBIRTHS` INT(11) DEFAULT 0 COMMENT 'Number of stillbirths' AFTER `PRG_LIVING_CHILDREN`,
    ADD COLUMN IF NOT EXISTS `PRG_DECEASED_CHILDREN` INT(11) DEFAULT 0 COMMENT 'Number of deceased children' AFTER `PRG_STILLBIRTHS`,
    ADD COLUMN IF NOT EXISTS `PRG_DESIRED_CHILDREN` INT(11) DEFAULT NULL COMMENT 'Desired total number of children' AFTER `PRG_DECEASED_CHILDREN`,
    ADD COLUMN IF NOT EXISTS `PRG_BREASTFEEDING` CHAR(1) DEFAULT NULL COMMENT 'Breastfeeding status (Y/N)' AFTER `PRG_DESIRED_CHILDREN`,
    ADD COLUMN IF NOT EXISTS `PRG_LAST_CHILD_YEARS` INT(11) DEFAULT NULL COMMENT 'Last child age - years' AFTER `PRG_BREASTFEEDING`,
    ADD COLUMN IF NOT EXISTS `PRG_LAST_CHILD_MONTHS` INT(11) DEFAULT NULL COMMENT 'Last child age - months' AFTER `PRG_LAST_CHILD_YEARS`,
    ADD COLUMN IF NOT EXISTS `PRG_LAST_CHILD_WEEKS` INT(11) DEFAULT NULL COMMENT 'Last child age - weeks' AFTER `PRG_LAST_CHILD_MONTHS`,
    ADD COLUMN IF NOT EXISTS `PRG_LAST_CHILD_DAYS` INT(11) DEFAULT NULL COMMENT 'Last child age - days' AFTER `PRG_LAST_CHILD_WEEKS`;