-- ========================================================================
-- HIV Infant Follow-up Module - Complete database setup
-- ========================================================================
-- This script creates all tables for the HIV infant follow-up module:
--   1. OH_HIV_INFANT      - Infants enrolled in the HIV program
--   2. OH_HIV_VISIT       - Follow-up visits for HIV infants
--   3. Typologies         - HIV treatment types (Family: HIV_TREATMENT_TYPE)
-- ========================================================================
-- Treatments are managed via the existing Therapy module with Typology
-- ========================================================================

-- ========================================================================
-- 1. Table: OH_HIV_INFANT
--    Main table storing HIV infant information
--    Links to OH_PATIENT for the infant and optionally the mother
-- ========================================================================

CREATE TABLE IF NOT EXISTS OH_HIV_INFANT (
    HVI_ID INT NOT NULL AUTO_INCREMENT,
    HVI_PAT_ID INT NOT NULL,
    HVI_MOTHER_PAT_ID INT NULL,
    HVI_REG_DATE DATETIME NOT NULL,
    HVI_BIRTH_WEIGHT DOUBLE NULL,
    HVI_GESTATIONAL_AGE INT NULL,
    HVI_FEEDING_TYPE VARCHAR(20) NULL,
    HVI_STATUS VARCHAR(20) NOT NULL,
    HVI_FOLLOWUP_START DATE NOT NULL,
    HVI_FOLLOWUP_END DATE NULL,
    HVI_NOTES TEXT NULL,
    HVI_LOCK INT DEFAULT 0,
    HVI_CREATED_BY VARCHAR(50) NOT NULL,
    HVI_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    HVI_LAST_MODIFIED_BY VARCHAR(50) NULL,
    HVI_LAST_MODIFIED_DATE DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    HVI_ACTIVE TINYINT(1) DEFAULT 1,
    PRIMARY KEY (HVI_ID),
    FOREIGN KEY (HVI_PAT_ID) REFERENCES OH_PATIENT(PAT_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (HVI_MOTHER_PAT_ID) REFERENCES OH_PATIENT(PAT_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    INDEX idx_hiv_infant_pat (HVI_PAT_ID),
    INDEX idx_hiv_infant_status (HVI_STATUS),
    INDEX idx_hiv_infant_reg_date (HVI_REG_DATE)
    ) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- ========================================================================
-- 2. Table: OH_HIV_VISIT
--    Follow-up visits for HIV infants
--    Links to OH_HIV_INFANT (one infant can have many visits)
-- ========================================================================

CREATE TABLE IF NOT EXISTS OH_HIV_VISIT (
    HVV_ID INT NOT NULL AUTO_INCREMENT,
    HVV_HVI_ID INT NOT NULL,
    HVV_VISIT_DATE DATETIME NOT NULL,
    HVV_WEIGHT DOUBLE NULL,
    HVV_HEIGHT DOUBLE NULL,
    HVV_HEAD_CIRCUMFERENCE DOUBLE NULL,
    HVV_TEMPERATURE DOUBLE NULL,
    HVV_CLINICAL_STATUS TEXT NULL,
    HVV_MILESTONES VARCHAR(255) NULL,
    HVV_PCR_RESULT VARCHAR(20) NULL,
    HVV_VIRAL_LOAD DOUBLE NULL,
    HVV_CD4_COUNT INT NULL,
    HVV_CD4_PERCENT INT NULL,
    HVV_HEMOGLOBIN DOUBLE NULL,
    HVV_ADHERENCE INT NULL,
    HVV_SIDE_EFFECTS TEXT NULL,
    HVV_NEXT_APPOINTMENT_DATE DATE NULL,
    HVV_NOTES TEXT NULL,
    HVV_LOCK INT DEFAULT 0,
    HVV_CREATED_BY VARCHAR(50) NOT NULL,
    HVV_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    HVV_LAST_MODIFIED_BY VARCHAR(50) NULL,
    HVV_LAST_MODIFIED_DATE DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    HVV_ACTIVE TINYINT(1) DEFAULT 1,
    PRIMARY KEY (HVV_ID),
    FOREIGN KEY (HVV_HVI_ID) REFERENCES OH_HIV_INFANT(HVI_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_hiv_visit_infant (HVV_HVI_ID),
    INDEX idx_hiv_visit_date (HVV_VISIT_DATE)
    ) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

-- ========================================================================
-- 3. Typology for HIV Treatments
--    Family: HIV_TREATMENT_TYPE
-- ========================================================================

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_PROPHYLAXIS_NEV', 'Nevirapine Prophylaxis', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_PROPHYLAXIS_NEV');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_PROPHY_AZT', 'AZT Prophylaxis', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_PROPHY_AZT');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_PROPHY_AZT_NVP', 'AZT+NVP Prophylaxis', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_PROPHY_AZT_NVP');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_PROPHY_BACTRIM', 'Bactrim Prophylaxis', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_PROPHY_BACTRIM');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_PROPHY_OTHER', 'Other Prophylaxis', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_PROPHY_OTHER');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_ARV_AZT', 'AZT ARV', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_ARV_AZT');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_ARV_LAMIVUDINE', 'Lamivudine ARV', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_ARV_LAMIVUDINE');

INSERT INTO OH_TYPOLOGIES (TYPO_CODE, TYPO_DESCRIPTION, TYPO_FAMILY, TYPO_CREATED_BY, TYPO_CREATED_DATE, TYPO_ACTIVE)
SELECT * FROM (SELECT 'HIV_ARV_ABACAVIR', 'Abacavir ARV', 'HIV_TREATMENT_TYPE', 'admin', NOW(), 1) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_TYPOLOGIES WHERE TYPO_CODE = 'HIV_ARV_ABACAVIR');

DROP TABLE IF EXISTS OH_HIV_TREATMENT;