CREATE TABLE IF NOT EXISTS OH_OUTDIAGNOSIS (
  OD_ADM_ID INT NOT NULL,
  OD_DIS_ID_A VARCHAR(10) NOT NULL,
  OD_LOCK INT NOT NULL DEFAULT 0,
  OD_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  OD_CREATED_BY VARCHAR(50),
  OD_CREATED_DATE DATETIME,
  OD_LAST_MODIFIED_BY VARCHAR(50),
  OD_LAST_MODIFIED_DATE DATETIME,

  PRIMARY KEY (OD_ADM_ID, OD_DIS_ID_A),

  CONSTRAINT FK_OUT_ADMISSION
    FOREIGN KEY (OD_ADM_ID)
    REFERENCES OH_ADMISSION (ADM_ID),

  CONSTRAINT FK_OUT_DISEASE
    FOREIGN KEY (OD_DIS_ID_A)
    REFERENCES OH_DISEASE (DIS_ID_A)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;