CREATE TABLE OH_COMPLICATIONDIAGNOSIS (
  CD_ADM_ID INT NOT NULL,
  CD_DIS_ID_A VARCHAR(10) NOT NULL,

  PRIMARY KEY (CD_ADM_ID, CD_DIS_ID_A),

  CONSTRAINT FK_COMP_ADMISSION
    FOREIGN KEY (CD_ADM_ID)
    REFERENCES OH_ADMISSION (ADM_ID),

  CONSTRAINT FK_COMP_DISEASE
    FOREIGN KEY (CD_DIS_ID_A)
    REFERENCES OH_DISEASE (DIS_ID_A)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;