CREATE TABLE IF NOT EXISTS OH_ADMISSIONDIAGNOSIS (
    ADMD_ADM_ID INT NOT NULL,
    ADMD_DIS_ID_A VARCHAR(10) NOT NULL,
    ADMD_LOCK INT NOT NULL DEFAULT 0,
    ADMD_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    ADMD_CREATED_BY VARCHAR(50),
    ADMD_CREATED_DATE DATETIME,
    ADMD_LAST_MODIFIED_BY VARCHAR(50),
    ADMD_LAST_MODIFIED_DATE DATETIME,

    PRIMARY KEY (ADMD_ADM_ID, ADMD_DIS_ID_A),

    INDEX IDX_OPDD_OPD_ID (ADMD_ADM_ID),
    INDEX IDX_OPDD_DIS_ID (ADMD_DIS_ID_A),

    CONSTRAINT FK_ADMD_ADMISSION FOREIGN KEY (ADMD_ADM_ID) REFERENCES OH_ADMISSION(ADM_ID),
    CONSTRAINT FK_ADMD_DISEASE FOREIGN KEY (ADMD_DIS_ID_A) REFERENCES OH_DISEASE(DIS_ID_A)

) ENGINE=MyISAM;