-- Create OH_BLOCK and OH_BLOCK_EXAM tables for block exam grouping
-- Note: must use utf8mb3 charset to match OH_EXAM (for FK compatibility)
CREATE TABLE IF NOT EXISTS OH_BLOCK (
    BLO_CODE VARCHAR(20) NOT NULL,
    BLO_DESC VARCHAR(100) NOT NULL,
    PRIMARY KEY (BLO_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS OH_BLOCK_EXAM (
    BLE_ID INT(11) NOT NULL AUTO_INCREMENT,
    BLE_BLO_CODE VARCHAR(20) NOT NULL,
    BLE_EXA_ID_A VARCHAR(10) NOT NULL,
    PRIMARY KEY (BLE_ID),
    KEY FK_BLOCK_EXAM_BLOCK_IDX (BLE_BLO_CODE ASC),
    KEY FK_BLOCK_EXAM_EXAM_IDX (BLE_EXA_ID_A ASC),
    CONSTRAINT FK_BLOCK_EXAM_BLOCK FOREIGN KEY (BLE_BLO_CODE) REFERENCES OH_BLOCK (BLO_CODE) ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT FK_BLOCK_EXAM_EXAM FOREIGN KEY (BLE_EXA_ID_A) REFERENCES OH_EXAM (EXA_ID_A) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;