ALTER TABLE oh_bills ADD COLUMN IF NOT EXISTS BLL_PARENT_ID INT DEFAULT NULL;
ALTER TABLE oh_bills ADD INDEX IF NOT EXISTS idx_bills_parent_id (BLL_PARENT_ID);
ALTER TABLE oh_billitems ADD COLUMN IF NOT EXISTS BLI_DATE DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE oh_billitems ADD INDEX IF NOT EXISTS idx_billitems_date (BLI_DATE);
UPDATE oh_billitems bi INNER JOIN oh_bills b ON bi.BLI_ID_BILL = b.BLL_ID SET bi.BLI_DATE = b.BLL_DATE WHERE bi.BLI_DATE IS NULL;
ALTER TABLE oh_bills ADD COLUMN IF NOT EXISTS BLL_GARANTE VARCHAR(100) DEFAULT NULL;
ALTER TABLE oh_bills ADD COLUMN IF NOT EXISTS BLL_IS_CLOSED_MANUALLY TINYINT(1) DEFAULT 0;