-- ============================================================
--  CPN module (Consultation Prénatale) — Phase 1/5
--  Tables: OH_PREGNANCY, OH_PREGNANCYVISIT, OH_PREGNANCYVISITTREATMENTTYPE,
--          OH_PREGNANCYEXAM (configurable "paramètres CPN" catalog),
--          OH_PREGNANCYEXAMRESULT
-- ============================================================

CREATE TABLE IF NOT EXISTS OH_PREGNANCY (
    PREG_ID                   INT AUTO_INCREMENT PRIMARY KEY,
    PREG_NR                   INT          NOT NULL DEFAULT 1,
    PREG_PAT_ID                INT          NOT NULL,
    PREG_LMP                  DATE         NOT NULL,
    PREG_CALC_DELIVERY        DATE         NOT NULL,
    PREG_NB_GROSS              INT          NOT NULL DEFAULT 0,
    PREG_NB_ACCT               INT          NOT NULL DEFAULT 0,
    PREG_NB_ACCP               INT          NOT NULL DEFAULT 0,
    PREG_NB_AVORT              INT          NOT NULL DEFAULT 0,
    PREG_NB_ENF_VIV            INT          NOT NULL DEFAULT 0,
    PREG_NB_ENF_MRT_NEE        INT          NOT NULL DEFAULT 0,
    PREG_NB_ENF_DEC            INT          NOT NULL DEFAULT 0,
    PREG_NB_ENF_DES            INT          NOT NULL DEFAULT 0,
    PREG_AGE_LAST              INT          DEFAULT NULL,
    PREG_ALLAIT                TINYINT(1)   NOT NULL DEFAULT 0,
    PREG_CREATED_BY            VARCHAR(50)  DEFAULT NULL,
    PREG_CREATED_DATE          DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PREG_LAST_MODIFIED_BY      VARCHAR(50)  DEFAULT NULL,
    PREG_LAST_MODIFIED_DATE    DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PREG_ACTIVE                TINYINT(1)   NOT NULL DEFAULT 1,

    CONSTRAINT FK_PREGNANCY_PATIENT FOREIGN KEY (PREG_PAT_ID) REFERENCES PATIENT(PAT_ID),
    INDEX IDX_PREG_PAT_ID (PREG_PAT_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS OH_PREGNANCYEXAM (
    PREGEX_CODE                VARCHAR(10)  NOT NULL PRIMARY KEY,
    PREGEX_DESC                VARCHAR(100) NOT NULL,
    PREGEX_TYPE                TINYINT      NOT NULL DEFAULT 0,
    PREGEX_DATA_TYPE           VARCHAR(10)  NOT NULL DEFAULT 'TEXT',
    PREGEX_DEFAULT             VARCHAR(100) DEFAULT NULL,
    PREGEX_VALUES              VARCHAR(255) DEFAULT NULL,
    PREGEX_MAX_VALUE           DOUBLE       DEFAULT NULL,
    PREGEX_UNIT                VARCHAR(20)  DEFAULT NULL,
    PREGEX_CREATED_BY          VARCHAR(50)  DEFAULT NULL,
    PREGEX_CREATED_DATE        DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PREGEX_LAST_MODIFIED_BY    VARCHAR(50)  DEFAULT NULL,
    PREGEX_LAST_MODIFIED_DATE  DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PREGEX_ACTIVE               TINYINT(1)   NOT NULL DEFAULT 1
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS OH_PREGNANCYVISIT (
    PVIS_ID                    INT AUTO_INCREMENT PRIMARY KEY,
    PVIS_PREG_ID               INT          NOT NULL,
    PVIS_PAT_ID                INT          NOT NULL,
    PVIS_DATE                  DATETIME     NOT NULL,
    PVIS_NEXTDATE               DATETIME     DEFAULT NULL,
    PVIS_TYPE                  TINYINT      NOT NULL DEFAULT -1,
    PVIS_NOTE                  TEXT,
    PVIS_CREATED_BY             VARCHAR(50)  DEFAULT NULL,
    PVIS_CREATED_DATE           DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PVIS_LAST_MODIFIED_BY       VARCHAR(50)  DEFAULT NULL,
    PVIS_LAST_MODIFIED_DATE     DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PVIS_ACTIVE                 TINYINT(1)   NOT NULL DEFAULT 1,

    CONSTRAINT FK_PREGNANCYVISIT_PREGNANCY FOREIGN KEY (PVIS_PREG_ID) REFERENCES OH_PREGNANCY(PREG_ID),
    CONSTRAINT FK_PREGNANCYVISIT_PATIENT FOREIGN KEY (PVIS_PAT_ID) REFERENCES PATIENT(PAT_ID),
    INDEX IDX_PVIS_PREG_ID (PVIS_PREG_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS OH_PREGNANCYVISITTREATMENTTYPE (
    PVTT_PVIS_ID                INT          NOT NULL,
    PVTT_PTT_ID_A               VARCHAR(10)  NOT NULL,

    PRIMARY KEY (PVTT_PVIS_ID, PVTT_PTT_ID_A),
    CONSTRAINT FK_PREGNANCYVISITTT_VISIT FOREIGN KEY (PVTT_PVIS_ID) REFERENCES OH_PREGNANCYVISIT(PVIS_ID),
    CONSTRAINT FK_PREGNANCYVISITTT_TYPE FOREIGN KEY (PVTT_PTT_ID_A) REFERENCES OH_PREGNANTTREATMENTTYPE(PTT_ID_A)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS OH_PREGNANCYEXAMRESULT (
    PEXRES_ID                   INT AUTO_INCREMENT PRIMARY KEY,
    PEXRES_PVIS_ID               INT          NOT NULL,
    PEXRES_PREGEX_CODE           VARCHAR(10)  NOT NULL,
    PEXRES_OUTCOME               VARCHAR(255) DEFAULT NULL,
    PEXRES_CREATED_BY            VARCHAR(50)  DEFAULT NULL,
    PEXRES_CREATED_DATE          DATETIME     DEFAULT CURRENT_TIMESTAMP,
    PEXRES_LAST_MODIFIED_BY      VARCHAR(50)  DEFAULT NULL,
    PEXRES_LAST_MODIFIED_DATE    DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PEXRES_ACTIVE                 TINYINT(1)   NOT NULL DEFAULT 1,

    CONSTRAINT FK_PREGNANCYEXAMRESULT_VISIT FOREIGN KEY (PEXRES_PVIS_ID) REFERENCES OH_PREGNANCYVISIT(PVIS_ID),
    CONSTRAINT FK_PREGNANCYEXAMRESULT_EXAM FOREIGN KEY (PEXRES_PREGEX_CODE) REFERENCES OH_PREGNANCYEXAM(PREGEX_CODE),
    INDEX IDX_PEXRES_PVIS_ID (PEXRES_PVIS_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

-- ============================================================
-- SEED: standard + bounded CPN parameters
-- PREGEX_TYPE: -1 = prenatal only, 1 = postnatal only, 0 = both
-- ============================================================
INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'MW' AS c, 'Poids de la mère' AS d, 0 AS t, 'NUMERIC' AS dt, NULL AS def, NULL AS vals, 300.0 AS mx, 'kg' AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'MW');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'BP' AS c, 'Tension artérielle' AS d, 0 AS t, 'TEXT' AS dt, NULL AS def, NULL AS vals, NULL AS mx, 'mmHg' AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'BP');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'FHR' AS c, 'Fréquence cardiaque fœtale' AS d, -1 AS t, 'NUMERIC' AS dt, NULL AS def, NULL AS vals, 200.0 AS mx, 'bpm' AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'FHR');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'CONJ' AS c, 'Conjonctives' AS d, -1 AS t, 'ENUM' AS dt, NULL AS def, 'Colorées;Moins colorées;Pâles' AS vals, NULL AS mx, NULL AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'CONJ');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'HU' AS c, 'Hauteur utérine' AS d, -1 AS t, 'NUMERIC' AS dt, NULL AS def, NULL AS vals, 60.0 AS mx, 'cm' AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'HU');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'CA' AS c, 'Circonférence abdominale' AS d, -1 AS t, 'NUMERIC' AS dt, NULL AS def, NULL AS vals, 200.0 AS mx, 'cm' AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'CA');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'PRES' AS c, 'Présentation' AS d, -1 AS t, 'ENUM' AS dt, NULL AS def,
    'Céphalique - Mobile;Céphalique - Amorcé;Céphalique - Fixe;Transverse;Siège' AS vals, NULL AS mx, NULL AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'PRES');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'BDCF' AS c, 'Bruit du cœur fœtal' AS d, -1 AS t, 'NUMERIC' AS dt, NULL AS def, NULL AS vals, 200.0 AS mx, 'bpm' AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'BDCF');

INSERT INTO OH_PREGNANCYEXAM (PREGEX_CODE, PREGEX_DESC, PREGEX_TYPE, PREGEX_DATA_TYPE, PREGEX_DEFAULT, PREGEX_VALUES, PREGEX_MAX_VALUE, PREGEX_UNIT)
SELECT * FROM (SELECT 'OEDEME' AS c, 'Œdèmes' AS d, -1 AS t, 'ENUM' AS dt, 'Négatif' AS def, 'Négatif;Positif' AS vals, NULL AS mx, NULL AS u) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM OH_PREGNANCYEXAM WHERE PREGEX_CODE = 'OEDEME');

-- ============================================================
-- ADD CPN MENU ITEMS
-- ============================================================
INSERT INTO oh_menuitem
(MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION)
SELECT
    'cpn',
    'angal.menu.btn.cpn',
    'angal.menu.cpn',
    'x',
    'P',
    'main',
    'org.isf.pregnancy.gui.CpnBrowser',
    'N',
    8
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM oh_menuitem WHERE MNI_ID_A = 'cpn'
);

INSERT INTO oh_menuitem
(MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION)
SELECT
    'cpnexam',
    'angal.menu.btn.cpnexam',
    'angal.menu.cpnexam',
    'x',
    'E',
    'generaldata',
    'org.isf.pregnancy.gui.CpnExamParameterBrowser',
    'N',
    9
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM oh_menuitem WHERE MNI_ID_A = 'cpnexam'
);

-- =========================
-- GROUP MENU
-- =========================
INSERT INTO oh_groupmenu
(GM_ID, GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE, GM_CREATED_BY, GM_CREATED_DATE, GM_LAST_MODIFIED_BY, GM_LAST_MODIFIED_DATE)
SELECT
    (SELECT COALESCE(MAX(GM_ID), 0) + 1 FROM oh_groupmenu),
    'admin',
    'cpn',
    1,
    NULL,
    NULL,
    NULL,
    NULL
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM oh_groupmenu WHERE GM_MNI_ID_A = 'cpn' AND GM_UG_ID_A = 'admin'
);

INSERT INTO oh_groupmenu
(GM_ID, GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE, GM_CREATED_BY, GM_CREATED_DATE, GM_LAST_MODIFIED_BY, GM_LAST_MODIFIED_DATE)
SELECT
    (SELECT COALESCE(MAX(GM_ID), 0) + 1 FROM oh_groupmenu),
    'admin',
    'cpnexam',
    1,
    NULL,
    NULL,
    NULL,
    NULL
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM oh_groupmenu WHERE GM_MNI_ID_A = 'cpnexam' AND GM_UG_ID_A = 'admin'
);
