ALTER TABLE OH_OPD ADD OPD_PRESCRIPTION VARCHAR(255);

ALTER TABLE `OH_OPD`
    ADD COLUMN `OPD_MALNUTRITION` CHAR(1) DEFAULT 'N' COMMENT 'Malnutrition status (Y/N)' AFTER `OPD_NEXT_VISIT_ID`,
    ADD COLUMN `OPD_REASON` VARCHAR(255) DEFAULT NULL COMMENT 'Referral reason (motif)' AFTER `OPD_MALNUTRITION`;