ALTER TABLE OH_BILLS
    ADD COLUMN BLL_RP_ID INT NULL DEFAULT NULL,
    ADD COLUMN BLL_WARD_ID VARCHAR(10) NULL DEFAULT NULL AFTER BLL_RP_ID,

    ADD CONSTRAINT FK_BILLS_REDUCTIONPLAN
        FOREIGN KEY (BLL_RP_ID)
        REFERENCES OH_REDUCTIONPLAN(RP_ID),

    ADD CONSTRAINT FK_BILLS_WARD
        FOREIGN KEY (BLL_WARD_ID)
        REFERENCES OH_WARD(WRD_ID_A);