-- drop the existing table
drop table if exists oh_settings;

-- create settings table structure
create table oh_settings (
                             sett_id int(11) not null auto_increment comment 'default generated ID',
                             sett_code varchar(50) not null,
                             sett_category enum('general', 'application', 'gui', 'accounting', 'pharmacy', 'imaging', 'reports', 'security', 'telemetry', 'integration') not null default 'general',
                             sett_value_type enum('bool', 'number', 'text', 'select') not null default 'text',
                             sett_value_options varchar(500) null default null comment "Comma-separated list of possible values, in case of type 'select'",
                             sett_default_value varchar(255) not null,
                             sett_value varchar(255) not null,
                             sett_description varchar(500) null,
                             sett_created_by varchar(50) null default null,
                             sett_created_date datetime not null default current_timestamp(),
                             sett_last_modified_by varchar(50) null default null,
                             sett_last_modified_date datetime null default null,
                             sett_active tinyint(1) not null default 1,
                             sett_need_restart tinyint(1) not null default 1,
                             primary key (sett_id),
                             constraint setting_unique_code unique (sett_code)
) engine=innodb;

-- create permissions for settings
insert into `oh_permissions` (`p_id_a`, `p_name`, `p_description`, `p_active`, `p_created_by`, `p_created_date`, `p_last_modified_by`, `p_last_modified_date`) values (174,'settings.read','','1',null,null,null,null);
insert into `oh_permissions` (`p_id_a`, `p_name`, `p_description`, `p_active`, `p_created_by`, `p_created_date`, `p_last_modified_by`, `p_last_modified_date`) values (175,'settings.update','','1',null,null,null,null);

-- assign setting permissions to admin group
insert into `oh_grouppermission` (`gp_id`, `gp_ug_id_a`, `gp_p_id_a`, `gp_active`, `gp_created_by`, `gp_created_date`, `gp_last_modified_by`, `gp_last_modified_date`) values (321,'admin',174,'1',null,null,null,null);
insert into `oh_grouppermission` (`gp_id`, `gp_ug_id_a`, `gp_p_id_a`, `gp_active`, `gp_created_by`, `gp_created_date`, `gp_last_modified_by`, `gp_last_modified_date`) values (322,'admin',175,'1',null,null,null,null);

-- load settings into the database
insert into `oh_settings` (`sett_id`, `sett_code`, `sett_value_type`, `sett_value_options`, `sett_default_value`, `sett_value`, `sett_description`, `sett_created_by`, `sett_last_modified_by`, `sett_created_date`, `sett_last_modified_date`, `sett_active`, `sett_need_restart`, `sett_category`) values
                                                                                                                                                                                                                                                                                                         (null, 'singleuser', 'bool', null, 'false', 'false', 'Make the software to work with only one user', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'language', 'select', 'am_ET,ar,ar_SA,de,en,es,fr,it,pt,sq,sw,zh_CN', 'en', 'en', 'Display language', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'doc_dir', 'text', null, '../doc', '../doc', 'Directory path in which user guides are stored', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'internalviewer', 'bool', null, 'true', 'true', 'Use the internal viewer', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'viewer', 'text', null, '', '', 'Path to custom pdf viewer', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'xmppmoduleenabled', 'bool', null, 'false', 'false', 'Whether to enable xmpp module or not', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'patientphotostorage', 'text', null, '', '', 'Path to the directory where patient photos are stored', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'debug', 'bool', null, 'false', 'false', 'Use debug mode', 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'mainmenualwaysontop', 'bool', null, 'false', 'false', 'Always display main menu window on top', 'admin', null, now(), null, 1, 1, 'gui'),
                                                                                                                                                                                                                                                                                                         (null, 'patientextended', 'bool', null, 'false', 'false', 'Enable extended patient form', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'opdextended', 'bool', null, 'false', 'false', 'Enable extended opd form', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'labextended', 'bool', null, 'false', 'false', 'Enable extended laboratory', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'patientvaccineextended', 'bool', null, 'false', 'false', 'Use extended patient vaccine', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'mergefunction', 'bool', null, 'true', 'true', 'Enable patient merge feature', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'smsenabled', 'bool', null, 'false', 'false', 'Enable sms sending', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'videomoduleenabled', 'bool', null, 'false', 'false', 'Whether to enable Video module or not', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'enhancedsearch', 'bool', null, 'false', 'false', 'Enable enhanced search', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'labmultipleinsert', 'bool', null, 'false', 'false', 'Use multiple insert for lab exams', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'maternityrestartinjune', 'bool', null, 'false', 'false', 'Restart maternity in June', 'admin', null, now(), null, 1, 1, 'application'),
                                                                                                                                                                                                                                                                                                         (null, 'telemetryenabled', 'bool', null, 'false', 'false', 'Enable telemetry', 'admin', null, now(), null, 1, 1, 'telemetry'),
                                                                                                                                                                                                                                                                                                         (null, 'userslistlogin', 'bool', null, 'false', 'false', 'Whether to show the list', 'admin', null, now(), null, 1, 1, 'security'),
                                                                                                                                                                                                                                                                                                         (null, 'sessiontimeout', 'number', null, '5', '5', 'Number in minute for session timeout', 'admin', null, now(), null, 1, 1, 'security'),
                                                                                                                                                                                                                                                                                                         (null, 'stronglength', 'number', null, '6', '6', 'The strength level of passwords', 'admin', null, now(), null, 1, 1, 'security'),
                                                                                                                                                                                                                                                                                                         (null, 'passwordtries', 'number', null, '5', '5', 'Number of password attempts before locking the account', 'admin', null, now(), null, 1, 1, 'security'),
                                                                                                                                                                                                                                                                                                         (null, 'passwordlocktime', 'number', null, '60', '60', 'Number in minutes for password lock time', 'admin', null, now(), null, 1, 1, 'security'),
                                                                                                                                                                                                                                                                                                         (null, 'passwordidle', 'number', null, '360', '360', 'Number in days of password validity', 'admin', null, now(), null, 1, 1, 'security'),
                                                                                                                                                                                                                                                                                                         (null, 'strongpassword', 'bool', null, 'true', 'false', 'Whether to required strong passwords or not', 'admin', null, now(), null, 1, 1, 'security'),
                                                                                                                                                                                                                                                                                                         (null, 'automaticlot_in', 'bool', null, 'true', 'true', 'Automatically create and assign lot to new stock entry mouvements', 'admin', null, now(), null, 1, 1, 'pharmacy'),
                                                                                                                                                                                                                                                                                                         (null, 'automaticlot_out', 'bool', null, 'true', 'true', 'Automatically create and assign lot to new stock out mouvements', 'admin', null, now(), null, 1, 1, 'pharmacy'),
                                                                                                                                                                                                                                                                                                         (null, 'automaticlotward_toward', 'bool', null, 'true', 'true', 'Automatically create and assign lot to ward to ward stock mouvements', 'admin', null, now(), null, 1, 1, 'pharmacy'),
                                                                                                                                                                                                                                                                                                         (null, 'internalpharmacies', 'bool', null, 'false', 'false', 'Allow internal pharmacies', 'admin', null, now(), null, 1, 1, 'pharmacy'),
                                                                                                                                                                                                                                                                                                         (null, 'lotwithcost', 'bool', null, 'true', 'true', 'Use lot with cost', 'admin', null, now(), null, 1, 1, 'pharmacy'),
                                                                                                                                                                                                                                                                                                         (null, 'receiptprinter', 'bool', null, 'false', 'false', 'Enable bill receipt printing', 'admin', null, now(), null, 1, 1, 'accounting'),
                                                                                                                                                                                                                                                                                                         (null, 'allowprintopenedbill', 'bool', null, 'false', 'false', 'Allow open bills printing', 'admin', null, now(), null, 1, 1, 'accounting'),
                                                                                                                                                                                                                                                                                                         (null, 'allowmultipleopenedbill', 'bool', null, 'false', 'true', 'Allow multiple open bills for a patient', 'admin', null, now(), null, 1, 1, 'accounting'),
                                                                                                                                                                                                                                                                                                         (null, 'dicommoduleenabled', 'bool', null, 'false', 'false', 'Whether to enable dicom module or not', 'admin', null, now(), null, 1, 1, 'imaging'),
                                                                                                                                                                                                                                                                                                         (null, 'dicomthumbnails', 'bool', null, 'true', 'true', 'Enable dicom thumbnails (previews)', 'admin', null, now(), null, 1, 1, 'imaging'),
                                                                                                                                                                                                                                                                                                         (null, 'patientsheet', 'text', null, 'patient_clinical_sheet', 'patient_clinical_sheet', 'File name for patient sheet report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'visitsheet', 'text', null, 'WardVisits', 'WardVisits', 'File name for visit sheet report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'billsreportpending', 'text', null, 'BillsReportPending', 'BillsReportPending', 'File name for pending bills report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'billsreportmonthly', 'text', null, 'BillsReportMonthly', 'BillsReportMonthly', 'File name for monthly bills report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'pharmaceuticalorder', 'text', null, 'PharmaceuticalOrder', 'PharmaceuticalOrder', 'File name for pharmaceuticals to order report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'pharmaceuticalstock', 'text', null, 'PharmaceuticalStock_ver4', 'PharmaceuticalStock_ver4', 'File name for pharmaceutical stock report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'pharmaceuticalstocklot', 'text', null, 'PharmaceuticalStock_ver5', 'PharmaceuticalStock_ver5', 'File name for pharmaceutical lots stock report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'pharmaceuticalamc', 'text', null, 'PharmaceuticalAMC', 'PharmaceuticalAMC', 'File name for pharmaceutical amc report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'patientbillgrouped', 'text', null, 'PatientBillGrouped', 'PatientBillGrouped', 'File name for patient bills grouped report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'patientbillstatement', 'text', null, 'PatientBillStatement', 'PatientBillStatement', 'File name for patient bills statement report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'examinationchart', 'text', null, 'patient_examination', 'patient_examination', 'File name for patient examination report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'opdchart', 'text', null, 'patient_opd_chart', 'patient_opd_chart', 'File name for opd chart report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'admchart', 'text', null, 'patient_adm_chart', 'patient_adm_chart', 'File name for admissions chart report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'dischart', 'text', null, 'patient_dis_chart', 'patient_dis_chart', 'File name for discharges chart report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'patientbill', 'text', null, 'PatientBill', 'PatientBill', 'File name for patient bill report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'billsreport', 'text', null, 'BillsReport', 'BillsReport', 'File name for bills report', 'admin', null, now(), null, 1, 1, 'reports'),
                                                                                                                                                                                                                                                                                                         (null, 'paramsurl', 'text', null, '', '', null, 'admin', null, now(), null, 1, 1, 'general'),
                                                                                                                                                                                                                                                                                                         (null, 'orthancbaseurl', 'text', null, '', '', 'Base url for orthanc api Server', 'admin', null, now(), null, 1, 1, 'integration'),
                                                                                                                                                                                                                                                                                                         (null, 'orthancexplorerurl', 'text', null, '', '', 'url of orthanc explorer', 'admin', null, now(), null, 1, 1, 'integration'),
                                                                                                                                                                                                                                                                                                         (null, 'orthancusername', 'text', null, '', '', 'Username of the user to use to authenticate orthanc api calls', 'admin', null, now(), null, 1, 1, 'integration'),
                                                                                                                                                                                                                                                                                                         (null, 'orthancpassword', 'text', null, '', '', 'Password of the user to use to authenticate orthanc api calls', 'admin', null, now(), null, 1, 1, 'integration'),
                                                                                                                                                                                                                                                                                                         (null, 'orthancenabled', 'bool', null, 'false', 'false', 'Whether to enable integration with orthanc or not', 'admin', null, now(), null, 1, 1, 'integration');
