ALTER TABLE OH_DEATHREASON DROP KEY DTHR_CODE;

ALTER TABLE OH_DEATHREASON CHANGE COLUMN DTHR_CODE DTHR_TITLE VARCHAR(255) NOT NULL;

ALTER TABLE OH_DEATHREASON MODIFY COLUMN DTHR_DESC TEXT NOT NULL;

INSERT INTO `oh_menuitem` (`MNI_ID_A`, `MNI_BTN_LABEL`, `MNI_LABEL`, `MNI_TOOLTIP`, `MNI_SHORTCUT`, `MNI_SUBMENU`, `MNI_CLASS`, `MNI_IS_SUBMENU`, `MNI_POSITION`) VALUES ('deathreasons', 'angal.menu.btn.causeofdeaths', 'angal.menu.causeofdeaths', 'x', 'A', 'mortuary', 'org.isf.mortuary.gui.DeathReasonBrowser','N', 4);

INSERT INTO `oh_groupmenu` (`GM_ID`, `GM_UG_ID_A`, `GM_MNI_ID_A`, `GM_ACTIVE`, `GM_CREATED_BY`, `GM_CREATED_DATE`, `GM_LAST_MODIFIED_BY`, `GM_LAST_MODIFIED_DATE`) VALUES (355,'admin','deathreasons',1,NULL,NULL,NULL,NULL);