-- Add LAB_PRESCRIBER and LAB_BLL_ID columns to OH_LABORATORY
-- (idempotent: uses IF NOT EXISTS to avoid errors on re-run)
SET @sql_prescriber = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_LABORATORY' AND COLUMN_NAME = 'LAB_PRESCRIBER') = 0,
    'ALTER TABLE OH_LABORATORY ADD COLUMN LAB_PRESCRIBER VARCHAR(255) NULL DEFAULT NULL AFTER LAB_STATUS',
    'SELECT 1');
PREPARE stmt FROM @sql_prescriber;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql_bll = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_LABORATORY' AND COLUMN_NAME = 'LAB_BLL_ID') = 0,
    'ALTER TABLE OH_LABORATORY ADD COLUMN LAB_BLL_ID INT(11) NULL DEFAULT NULL AFTER LAB_PRESCRIBER',
    'SELECT 1');
PREPARE stmt FROM @sql_bll;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql_idx = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_LABORATORY' AND INDEX_NAME = 'FK_LABORATORY_BILL_IDX') = 0,
    'ALTER TABLE OH_LABORATORY ADD INDEX FK_LABORATORY_BILL_IDX (LAB_BLL_ID ASC)',
    'SELECT 1');
PREPARE stmt FROM @sql_idx;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql_fk = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'OH_LABORATORY' AND CONSTRAINT_NAME = 'FK_LABORATORY_BILL') = 0,
    'ALTER TABLE OH_LABORATORY ADD CONSTRAINT FK_LABORATORY_BILL FOREIGN KEY (LAB_BLL_ID) REFERENCES OH_BILLS (BLL_ID) ON DELETE NO ACTION ON UPDATE NO ACTION',
    'SELECT 1');
PREPARE stmt FROM @sql_fk;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
