-- Orthanc Config Access And lien Orthanc Patient to patient int OH

-- Create new table Orthanc config user access
CREATE TABLE OH_ORTHANC_USERS (
  ORU_ID int(11) NOT NULL AUTO_INCREMENT,
  ORU_USER_NAME VARCHAR(50) NOT NULL,
  ORU_US_ID_A varchar(50) NOT NULL, 
  ORU_PASSWORD VARCHAR(50) NOT NULL,
  ORU_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORU_CREATED_DATE datetime NULL DEFAULT NULL,
  ORU_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORU_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ORU_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (ORU_ID),
  FOREIGN KEY (ORU_US_ID_A) REFERENCES OH_USER(US_ID_A) ON DELETE CASCADE,
  UNIQUE (ORU_US_ID_A)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

-- Create new table for Orthanc patient 

CREATE TABLE OH_ORTHANC_PATIENT (
  ORP_ID int(11) NOT NULL AUTO_INCREMENT,
  ORP_PATIENT_ID VARCHAR(200) NOT NULL,
  ORP_PAT_ID_A int(11) NOT NULL, 
  ORP_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORP_CREATED_DATE datetime NULL DEFAULT NULL,
  ORP_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ORP_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ORP_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (ORP_ID),
  FOREIGN KEY (ORP_PAT_ID_A) REFERENCES OH_PATIENT(PAT_ID) ON DELETE CASCADE,
  UNIQUE (ORP_PAT_ID_A)
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

INSERT INTO `oh_orthanc_users`(`ORU_ID`, `ORU_USER_NAME`, `ORU_US_ID_A`, `ORU_PASSWORD`, `ORU_CREATED_BY`, `ORU_CREATED_DATE`, `ORU_LAST_MODIFIED_BY`, `ORU_LAST_MODIFIED_DATE`, `ORU_ACTIVE`) VALUES (1,'u2g','admin','u2g123',NULL,NULL,NULL,NULL,1);

-- update permission

INSERT INTO `oh_permissions` (`P_ID_A`, `P_NAME`, `P_DESCRIPTION`, `P_ACTIVE`, `P_CREATED_BY`, `P_CREATED_DATE`, `P_LAST_MODIFIED_BY`, `P_LAST_MODIFIED_DATE`) VALUES (167, 'orthanc.access','','1',NULL,NULL,NULL,NULL);
INSERT INTO `oh_permissions` (`P_ID_A`, `P_NAME`, `P_DESCRIPTION`, `P_ACTIVE`, `P_CREATED_BY`, `P_CREATED_DATE`, `P_LAST_MODIFIED_BY`, `P_LAST_MODIFIED_DATE`) VALUES (168, 'orthanc.read','','1',NULL,NULL,NULL,NULL);
INSERT INTO `oh_permissions` (`P_ID_A`, `P_NAME`, `P_DESCRIPTION`, `P_ACTIVE`, `P_CREATED_BY`, `P_CREATED_DATE`, `P_LAST_MODIFIED_BY`, `P_LAST_MODIFIED_DATE`) VALUES (169, 'orthanc.create','','1',NULL,NULL,NULL,NULL);
INSERT INTO `oh_permissions` (`P_ID_A`, `P_NAME`, `P_DESCRIPTION`, `P_ACTIVE`, `P_CREATED_BY`, `P_CREATED_DATE`, `P_LAST_MODIFIED_BY`, `P_LAST_MODIFIED_DATE`) VALUES (170, 'orthanc.update','','1',NULL,NULL,NULL,NULL);

-- update group_permission
INSERT INTO `oh_grouppermission` (`GP_ID`, `GP_UG_ID_A`, `GP_P_ID_A`, `GP_ACTIVE`, `GP_CREATED_BY`, `GP_CREATED_DATE`, `GP_LAST_MODIFIED_BY`, `GP_LAST_MODIFIED_DATE`) VALUES (313,'admin',168,'1',NULL,NULL,NULL,NULL);
INSERT INTO `oh_grouppermission` (`GP_ID`, `GP_UG_ID_A`, `GP_P_ID_A`, `GP_ACTIVE`, `GP_CREATED_BY`, `GP_CREATED_DATE`, `GP_LAST_MODIFIED_BY`, `GP_LAST_MODIFIED_DATE`) VALUES (314,'admin',169,'1',NULL,NULL,NULL,NULL);
INSERT INTO `oh_grouppermission` (`GP_ID`, `GP_UG_ID_A`, `GP_P_ID_A`, `GP_ACTIVE`, `GP_CREATED_BY`, `GP_CREATED_DATE`, `GP_LAST_MODIFIED_BY`, `GP_LAST_MODIFIED_DATE`) VALUES (315,'admin',170,'1',NULL,NULL,NULL,NULL);

