ALTER TABLE OH_MEDICALHISTORY
MODIFY COLUMN MH_VACC_STATE_PREV LONGTEXT NULL;

ALTER TABLE OH_MEDICALHISTORY
MODIFY COLUMN MH_VACC_STATE_NO_PREV LONGTEXT NULL;

ALTER TABLE OH_MEDICALHISTORY
ADD COLUMN MH_OTHER_PREGNANCY_SECTION LONGTEXT NULL;

ALTER TABLE OH_MEDICALHISTORY
ADD COLUMN MH_OTHER_VACC_STATE_SECTION LONGTEXT NULL;

ALTER TABLE OH_MEDICALHISTORY
ADD COLUMN MH_COMBINED_BREASTFEEDING VARCHAR(255) NULL;

ALTER TABLE OH_MEDICALHISTORY
ADD COLUMN MH_NOT_APPLICABLE_DEPARASITING BOOLEAN;