CREATE TABLE IF NOT EXISTS `OH_COUNTRY` (
    `CNT_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CNT_ISO_CODE` VARCHAR(2) NOT NULL,
    `CNT_PHONE_CODE` VARCHAR(10) NOT NULL,
    `CNT_NAME` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`CNT_ID`),
    UNIQUE KEY `uk_country_iso_code` (`CNT_ISO_CODE`),
    UNIQUE KEY `uk_country_phone_code` (`CNT_PHONE_CODE`),
    UNIQUE KEY `uk_country_name` (`CNT_NAME`)
    ) ENGINE=InnoDB;
