ALTER TABLE OH_PATIENT
    ADD COLUMN PAT_RP_ID INT NULL DEFAULT NULL,
    ADD COLUMN PAT_PL_ID INT NULL DEFAULT NULL;

ALTER TABLE OH_PATIENT ADD CONSTRAINT FK_PATIENT_PAT_RP_ID FOREIGN KEY (PAT_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID);

ALTER TABLE OH_PATIENT ADD CONSTRAINT FK_PATIENT_PAT_PL_ID FOREIGN KEY (PAT_PL_ID) REFERENCES OH_PRICELISTS (LST_ID);