
CREATE TABLE IF NOT EXISTS OH_TYPOLOGIES (
    TYPO_CODE VARCHAR(20) PRIMARY KEY,
    TYPO_DESCRIPTION VARCHAR(255) NOT NULL,
    TYPO_FAMILY VARCHAR(255) NOT NULL,

    -- Audit fields
    TYPO_CREATED_BY VARCHAR(50) NOT NULL,
    TYPO_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    TYPO_LAST_MODIFIED_BY VARCHAR(50),
    TYPO_LAST_MODIFIED_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    TYPO_ACTIVE BOOLEAN DEFAULT TRUE
) ENGINE=INNODB;