
ALTER TABLE OH_ADMISSION
ADD COLUMN ADM_REFERRING_CENTER VARCHAR(255) NULL,
ADD COLUMN ADM_REFERRAL_ALERT VARCHAR(255) NULL,
ADD COLUMN ADM_TRANSPORTATION_MODE VARCHAR(100) NULL,
ADD COLUMN ADM_REFERRAL_REASON TEXT NULL,
ADD COLUMN ADM_DIAGNOSIS TEXT NULL,
ADD COLUMN ADM_TREATMENT_RECEIVED TEXT NULL,
ADD COLUMN ADM_OUTCOME VARCHAR(255) NULL,
ADD COLUMN ADM_IMPROVEMENT_FEEDBACK TEXT NULL;
