--
-- Definition of table OH_BILLITEMGROUP
--

CREATE TABLE IF NOT EXISTS OH_BILLITEMGROUP (
  BLIG_ID INT(11) NOT NULL AUTO_INCREMENT,
  BLIG_TITLE VARCHAR(100) NOT NULL UNIQUE,
  BLIG_DESCRIPTION VARCHAR(500),
  BLIG_TOTAL DECIMAL(12, 2) NOT NULL DEFAULT 0,
  BLIG_LOCK INT(11) NOT NULL DEFAULT 0,
  BLIG_CREATED_BY VARCHAR(50) NOT NULL,
  BLIG_CREATED_DATE datetime NULL DEFAULT NULL,
  BLIG_LAST_MODIFIED_BY VARCHAR(50),
  BLIG_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  BLIG_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (BLIG_ID),
  CONSTRAINT FK_BILLITEMGROUP_CREATED_BY FOREIGN KEY (BLIG_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_BILLITEMGROUP_LAST_MODIFIED_BY FOREIGN KEY (BLIG_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;

--
-- Definition of table OH_BILLITEMGROUPITEM
--

CREATE TABLE IF NOT EXISTS OH_BILLITEMGROUPITEM (
  BLIGI_ID INT(11) NOT NULL AUTO_INCREMENT,
  BLIGI_BLIG_ID INT(11) NOT NULL,
  BLIGI_IS_PRICE TINYINT(1) NOT NULL DEFAULT 0,
  BLIGI_PRICE_ID VARCHAR(100),
  BLIGI_DESC VARCHAR(500),
  BLIGI_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0,
  BLIGI_QUANTITY INT(11) NOT NULL DEFAULT 1,
  BLIGI_LOCK INT(11) NOT NULL DEFAULT 0,
  BLIGI_CREATED_BY VARCHAR(50) NOT NULL,
  BLIGI_CREATED_DATE datetime NULL DEFAULT NULL,
  BLIGI_LAST_MODIFIED_BY VARCHAR(50),
  BLIGI_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  BLIGI_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (BLIGI_ID),
  CONSTRAINT FK_BILLITEMGROUPITEM_BLIG_ID FOREIGN KEY (BLIGI_BLIG_ID) REFERENCES OH_BILLITEMGROUP (BLIG_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_BILLITEMGROUPITEM_CREATED_BY FOREIGN KEY (BLIGI_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_BILLITEMGROUPITEM_LAST_MODIFIED_BY FOREIGN KEY (BLIGI_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARACTER SET utf8;