
ALTER TABLE OH_OPD
         ADD COLUMN IF NOT EXISTS OPD_REFERING_HOSP VARCHAR(255),
         ADD COLUMN IF NOT EXISTS OPD_RECEIVING_HOSP VARCHAR(255);
         ADD COLUMN `OPD_MALNUTRITION` CHAR(1) DEFAULT 'N' COMMENT 'Malnutrition status (Y/N)' AFTER `OPD_NEXT_VISIT_ID`,
         ADD COLUMN `OPD_REFERING_MOTIF` VARCHAR(255) DEFAULT NULL COMMENT 'Referral reason (motif)' AFTER `OPD_MALNUTRITION`;