ALTER TABLE OH_ADMISSION
ADD COLUMN ADM_REFERRAL_ALERT VARCHAR(255) NULL,
ADD COLUMN ADM_REFERRAL_REASON TEXT NULL,
ADD COLUMN ADM_TREATMENT_RECEIVED TEXT NULL,
ADD COLUMN ADM_OUTCOME VARCHAR(255) NULL,
ADD COLUMN ADM_IMPROVEMENT_FEEDBACK TEXT NULL,
ADD COLUMN ADM_DEATH_PERIOD VARCHAR(55) DEFAULT NULL;
