-- Add OH_PRESCRIBER table and its management screen (Settings > Types > Prescribers)

CREATE TABLE IF NOT EXISTS OH_PRESCRIBER (
    PRE_ID_A VARCHAR(10) NOT NULL,
    PRE_DESC VARCHAR(100) NOT NULL,
    PRE_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
    PRE_CREATED_DATE DATETIME NULL DEFAULT NULL,
    PRE_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
    PRE_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
    PRE_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (PRE_ID_A)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

INSERT IGNORE INTO OH_MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION)
VALUES ('prescriber', 'angal.prescriber.title', 'angal.prescriber.title', 'x', 'C', 'types', 'org.isf.prescriber.gui.PrescriberBrowser', 'N', 11);

INSERT INTO OH_GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE)
SELECT 'admin', 'prescriber', '1'
WHERE NOT EXISTS (SELECT 1 FROM OH_GROUPMENU WHERE GM_UG_ID_A = 'admin' AND GM_MNI_ID_A = 'prescriber');