ALTER TABLE OH_OPD
    ADD COLUMN IF NOT EXISTS OPD_REFERING_HOSP VARCHAR(255),
    ADD COLUMN IF NOT EXISTS OPD_RECEIVING_HOSP VARCHAR(255),
    ADD COLUMN IF NOT EXISTS OPD_MALNUTRITION TINYINT(1) DEFAULT 0 COMMENT 'Malnutrition status (1=Yes, 0=No)',
    ADD COLUMN IF NOT EXISTS OPD_REFERING_MOTIF VARCHAR(255) DEFAULT NULL COMMENT 'Referral reason (motif)';

ALTER TABLE OH_MALNUTRITIONCONTROL
    ADD COLUMN IF NOT EXISTS MLN_OPD_ID INT;

SET @constraint_exists = (
    SELECT COUNT(*)
    FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE  CONSTRAINT_SCHEMA = DATABASE()
      AND  TABLE_NAME        = 'OH_MALNUTRITIONCONTROL'
      AND  CONSTRAINT_NAME   = 'FK_MALNUTRITION_OPD'
);

SET @sql = IF(
    @constraint_exists = 0,
    'ALTER TABLE OH_MALNUTRITIONCONTROL ADD CONSTRAINT FK_MALNUTRITION_OPD FOREIGN KEY (MLN_OPD_ID) REFERENCES OH_OPD(OPD_ID)',
    'SELECT 1'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

ALTER TABLE OH_MALNUTRITIONCONTROL
    MODIFY COLUMN MLN_ADM_ID INT NULL;

INSERT INTO oh_menuitem
(
    MNI_ID_A,
    MNI_BTN_LABEL,
    MNI_LABEL,
    MNI_TOOLTIP,
    MNI_SHORTCUT,
    MNI_SUBMENU,
    MNI_CLASS,
    MNI_IS_SUBMENU,
    MNI_POSITION
)
SELECT
    'btnopdmalnutrition',
    'angal.opd.btn.malnutrition',
    'angal.opd.btn.malnutrition',
    'x',
    '',
    'opd_internal',
    '',
    'N',
    99
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM   oh_menuitem
    WHERE  MNI_ID_A = 'btnopdmalnutrition'
);

INSERT INTO oh_groupmenu
(
    GM_UG_ID_A,
    GM_MNI_ID_A,
    GM_ACTIVE,
    GM_CREATED_BY,
    GM_CREATED_DATE,
    GM_LAST_MODIFIED_BY,
    GM_LAST_MODIFIED_DATE
)
SELECT
    'admin',
    'btnopdmalnutrition',
    1,
    'admin',
    NOW(),
    'admin',
    NOW()
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM   oh_groupmenu
    WHERE  GM_UG_ID_A  = 'admin'
      AND  GM_MNI_ID_A = 'btnopdmalnutrition'
);

ALTER TABLE oh_usergroup
    ADD COLUMN IF NOT EXISTS UG_PERMISSIONS VARCHAR(1000) DEFAULT '';