CREATE TABLE IF NOT EXISTS OH_OPD_DIAGNOSIS (

    OPDD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    OPDD_OPD_ID INT NOT NULL,
    OPDD_DIS_ID_A VARCHAR(10) NOT NULL,
    OPDD_ORDER INT NOT NULL DEFAULT 0,
    OPDD_LOCK INT NOT NULL DEFAULT 0,
    OPDD_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    OPDD_CREATED_BY VARCHAR(50),
    OPDD_CREATED_DATE DATETIME,
    OPDD_LAST_MODIFIED_BY VARCHAR(50),
    OPDD_LAST_MODIFIED_DATE DATETIME,

    INDEX IDX_OPDD_OPD_ID (OPDD_OPD_ID),
    INDEX IDX_OPDD_DIS_ID (OPDD_DIS_ID_A),

    CONSTRAINT FK_OPDD_OPD FOREIGN KEY (OPDD_OPD_ID) REFERENCES OH_OPD(OPD_ID),
    CONSTRAINT FK_OPDD_DISEASE FOREIGN KEY (OPDD_DIS_ID_A) REFERENCES OH_DISEASE(DIS_ID_A)
    ) ENGINE=INNODB;