CREATE TABLE `oh_hospitalizationconsultation` (
  `HPC_ID` int NOT NULL AUTO_INCREMENT,
  `HPC_ENC_ID` int NOT NULL,
  `HPC_TEAMS` varchar(255) DEFAULT NULL,
  `HPC_DATE_TIME` datetime NOT NULL,
  `HPC_PARENT_COMPLAINTS` text,
  `HPC_PHYSICAL_EXAMINATION` text,
  `HPC_DIAGNOSIS` text,
  `HPC_MANAGEMENT_PLAN` text,
  `HPC_CREATED_BY` varchar(50) DEFAULT NULL,
  `HPC_CREATED_DATE` datetime DEFAULT NULL,
  `HPC_LAST_MODIFIED_BY` varchar(50) DEFAULT NULL,
  `HPC_LAST_MODIFIED_DATE` datetime DEFAULT NULL,
  `HPC_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `HPC_LOCK` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`HPC_ID`),
  CONSTRAINT `FK_HPC_ENC`
    FOREIGN KEY (`HPC_ENC_ID`)
    REFERENCES `oh_encounter` (`ENC_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;