DROP TABLE IF EXISTS OH_PREGNANCYDELIVERYTYPE;

CREATE TABLE OH_PREGNANCYDELIVERYTYPE (
    PRGDLVT_ID INT AUTO_INCREMENT PRIMARY KEY,

    PRGDLVT_CODE VARCHAR(5) PRIMARY KEY,
    PRGDLVT_DESCRIPTION VARCHAR(255) NOT NULL,

    PRGDLVT_ACTIVE BOOLEAN DEFAULT TRUE,

    -- Audit fields
    PRGDLVT_CREATED_BY VARCHAR(50) NOT NULL,
    PRGDLVT_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRGDLVT_LAST_MODIFIED_BY VARCHAR(50),
    PRGDLVT_LAST_MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) ENGINE = INNODB;