CREATE TABLE OH_REDUCTIONPLAN (
  RP_ID INT(11) NOT NULL AUTO_INCREMENT,
  RP_DESCRIPTION VARCHAR(100) NOT NULL,
  RP_OPERATIONRATE DECIMAL(5, 2) NOT NULL,
  RP_MEDICALRATE DECIMAL(5, 2) NOT NULL,
  RP_EXAMRATE DECIMAL(5, 2) NOT NULL,
  RP_OTHERRATE DECIMAL(5, 2) NOT NULL,
  RP_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  RP_LOCK INT(11) NOT NULL DEFAULT 0,
  RP_CREATED_BY VARCHAR(50) NOT NULL,
  RP_CREATED_DATE DATETIME NULL DEFAULT NULL,
  RP_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  RP_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  RP_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (RP_ID),
  CONSTRAINT FK_REDUCTIONPLAN_CREATED_BY FOREIGN KEY (RP_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_REDUCTIONPLAN_LAST_MODIFIED_BY FOREIGN KEY (RP_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_EXAMSREDUCTION (
  EXAR_ID INT(11) NOT NULL AUTO_INCREMENT,
  EXAR_RP_ID INT(11) NOT NULL,
  EXAR_EXA_ID_A VARCHAR(10) NOT NULL,
  EXAR_REDUCTIONRATE DECIMAL(5, 2) NOT NULL,
  EXAR_LOCK INT(11) NOT NULL DEFAULT 0,
  EXAR_CREATED_BY VARCHAR(50) NOT NULL,
  EXAR_CREATED_DATE DATETIME NULL DEFAULT NULL,
  EXAR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  EXAR_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  EXAR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (EXAR_ID),
  CONSTRAINT FK_EXAMSREDUCTION_RP_ID FOREIGN KEY (EXAR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_EXAMSREDUCTION_EXA_ID_A FOREIGN KEY (EXAR_EXA_ID_A) REFERENCES OH_EXAM (EXA_ID_A),
  CONSTRAINT FK_EXAMSREDUCTION_CREATED_BY FOREIGN KEY (EXAR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_EXAMSREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (EXAR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_MEDICALSREDUCTION (
  MR_ID INT(11) NOT NULL AUTO_INCREMENT,
  MR_RP_ID INT(11) NOT NULL,
  MR_MDSR_ID INT(11) NOT NULL,
  MR_REDUCTIONRATE DECIMAL(5, 2) NOT NULL,
  MR_LOCK INT(11) NOT NULL DEFAULT 0,
  MR_CREATED_BY VARCHAR(50) NOT NULL,
  MR_CREATED_DATE DATETIME NULL DEFAULT NULL,
  MR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  MR_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  MR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (MR_ID),
  CONSTRAINT FK_MEDICALSREDUCTION_RP_ID FOREIGN KEY (MR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_MEDICALSREDUCTION_MDSR_ID FOREIGN KEY (MR_MDSR_ID) REFERENCES OH_MEDICALDSR (MDSR_ID),
  CONSTRAINT FK_MEDICALSREDUCTION_CREATED_BY FOREIGN KEY (MR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_MEDICALSREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (MR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_OPERATIONSREDUCTION (
  OPR_ID INT(11) NOT NULL AUTO_INCREMENT,
  OPR_RP_ID INT(11) NOT NULL,
  OPR_OPE_ID_A VARCHAR(10) NOT NULL,
  OPR_REDUCTIONRATE DECIMAL(5, 2) NOT NULL,
  OPR_LOCK INT(11) NOT NULL DEFAULT 0,
  OPR_CREATED_BY VARCHAR(50) NOT NULL,
  OPR_CREATED_DATE DATETIME NULL DEFAULT NULL,
  OPR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  OPR_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  OPR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (OPR_ID),
  CONSTRAINT FK_OPERATIONSREDUCTION_RP_ID FOREIGN KEY (OPR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_OPERATIONSREDUCTION_OPE_ID_A FOREIGN KEY (OPR_OPE_ID_A) REFERENCES OH_OPERATION (OPE_ID_A),
  CONSTRAINT FK_OPERATIONSREDUCTION_CREATED_BY FOREIGN KEY (OPR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_OPERATIONSREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (OPR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_PRICESOTHERSREDUCTION (
  OTHR_ID INT(11) NOT NULL AUTO_INCREMENT,
  OTHR_RP_ID INT(11) NOT NULL,
  OTHR_OTH_ID INT(11) NOT NULL,
  OTHR_REDUCTIONRATE DECIMAL(5, 2) NOT NULL,
  OTHR_LOCK INT(11) NOT NULL DEFAULT 0,
  OTHR_CREATED_BY VARCHAR(50) NOT NULL,
  OTHR_CREATED_DATE DATETIME NULL DEFAULT NULL,
  OTHR_LAST_MODIFIED_BY VARCHAR(50) NOT NULL,
  OTHR_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  OTHR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (OTHR_ID),
  CONSTRAINT FK_PRICESOTHERSREDUCTION_RP_ID FOREIGN KEY (OTHR_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID),
  CONSTRAINT FK_PRICESOTHERSREDUCTION_OTH_ID FOREIGN KEY (OTHR_OTH_ID) REFERENCES OH_PRICESOTHERS (OTH_ID),
  CONSTRAINT FK_PRICESOTHERSREDUCTION_CREATED_BY FOREIGN KEY (OTHR_CREATED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PRICESOTHERSREDUCTION_LAST_MODIFIED_BY FOREIGN KEY (OTHR_LAST_MODIFIED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

ALTER TABLE OH_PATIENT ADD COLUMN PAT_RP_ID INT NULL DEFAULT NULL;
ALTER TABLE OH_PATIENT ADD CONSTRAINT FK_PATIENT_PAT_RP_ID FOREIGN KEY (PAT_RP_ID) REFERENCES OH_REDUCTIONPLAN (RP_ID);

INSERT INTO OH_MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION) VALUES ('reductionplan','angal.menu.btn.reductionplans','angal.menu.reductionplans','x','R','generaldata','org.isf.reductionplan.gui.ReductionPlanBrowser','N',11);
INSERT INTO OH_GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUES ('admin','reductionplan',1);
