ALTER TABLE OH_VACCINE ADD COLUMN VAC_MIN_STOCK_QTY INT DEFAULT NULL AFTER VAC_VACT_ID_A;

CREATE TABLE OH_VACCINESTOCKLOT (
	VSL_ID_A varchar(50) NOT NULL,
	VSL_VAC_ID_A varchar(10) NOT NULL,
	VSL_PREP_DATE datetime NOT NULL,
	VSL_DUE_DATE datetime NOT NULL,
	VSL_COST DOUBLE NULL,
	VSL_LOCK int NOT NULL default 0,
	VSL_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
	VSL_CREATED_DATE datetime NULL DEFAULT NULL,
	VSL_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
	VSL_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
	VSL_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (VSL_ID_A),
	FOREIGN KEY (VSL_VAC_ID_A) REFERENCES OH_VACCINE (VAC_ID_A),
	INDEX (VSL_VAC_ID_A),
	INDEX (VSL_DUE_DATE)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE OH_VACCINESTOCKMOVEMENT (
	VSM_ID int NOT NULL AUTO_INCREMENT,
	VSM_VAC_ID_A varchar(10) NOT NULL,
	VSM_VSL_ID_A varchar(50) NOT NULL,
	VSM_QTY int NOT NULL,
	VSM_REASON varchar(30) NOT NULL,
	VSM_DATE datetime NOT NULL,
	VSM_PAV_ID int NULL,
	VSM_NOTE varchar(255) NULL,
	VSM_LOCK int NOT NULL default 0,
	VSM_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
	VSM_CREATED_DATE datetime NULL DEFAULT NULL,
	VSM_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
	VSM_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
	VSM_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (VSM_ID),
	FOREIGN KEY (VSM_VAC_ID_A) REFERENCES OH_VACCINE (VAC_ID_A),
	FOREIGN KEY (VSM_VSL_ID_A) REFERENCES OH_VACCINESTOCKLOT (VSL_ID_A),
	FOREIGN KEY (VSM_PAV_ID) REFERENCES OH_PATIENTVACCINE (PAV_ID) ON DELETE SET NULL,
	INDEX (VSM_VAC_ID_A),
	INDEX (VSM_VSL_ID_A),
	INDEX (VSM_PAV_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

INSERT INTO OH_MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION) VALUES ('vaccinestock','angal.menu.btn.vaccinestock','angal.menu.vaccinestock','x','K','main','org.isf.vaccinestock.gui.VaccineStockBrowser','N',13);
INSERT INTO OH_MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION) VALUES ('btnvaccinestockcharge','angal.vaccinestock.charge','angal.vaccinestock.charge','x','C','vaccinestock','none','N',0);
INSERT INTO OH_MENUITEM (MNI_ID_A, MNI_BTN_LABEL, MNI_LABEL, MNI_TOOLTIP, MNI_SHORTCUT, MNI_SUBMENU, MNI_CLASS, MNI_IS_SUBMENU, MNI_POSITION) VALUES ('btnvaccinestockdischarge','angal.vaccinestock.discharge','angal.vaccinestock.discharge','x','D','vaccinestock','none','N',1);

INSERT INTO OH_GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUE ('admin','vaccinestock', 1);
INSERT INTO OH_GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUE ('admin','btnvaccinestockcharge', 1);
INSERT INTO OH_GROUPMENU (GM_UG_ID_A, GM_MNI_ID_A, GM_ACTIVE) VALUE ('admin','btnvaccinestockdischarge', 1);
