ALTER TABLE OH_PATIENT
    ADD COLUMN PAT_BIRTH_PLACE VARCHAR(100) DEFAULT NULL AFTER PAT_CITY,
    ADD COLUMN PAT_NBR_CHILDREN INT DEFAULT 0 AFTER PAT_BIRTH_PLACE,
    ADD COLUMN PAT_GEO_POS VARCHAR(30) DEFAULT NULL AFTER PAT_NBR_CHILDREN,
    ADD COLUMN PAT_PARENTS_RES VARCHAR(255) DEFAULT NULL AFTER PAT_GEO_POS,
    ADD COLUMN PAT_TRANSPORT VARCHAR(100) DEFAULT NULL AFTER PAT_PARENTS_RES,
    ADD COLUMN PAT_COUNTRY_ID INT DEFAULT NULL AFTER PAT_TRANSPORT,
    ADD COLUMN PAT_AFFILIATED_ID INT DEFAULT NULL AFTER PAT_COUNTRY_ID,
    ADD COLUMN PAT_BLAMA VARCHAR(255) NULL AFTER PAT_AFFILIATED_ID,
    ADD CONSTRAINT fk_patient_country
        FOREIGN KEY (PAT_COUNTRY_ID)
        REFERENCES OH_COUNTRY(CNT_ID);