insert into menuitem values ('data','angal.admission.data','angal.admission.data','x','D','admission','none','N',3);
insert into menuitem values ('btnadmnew','angal.admission.newpatient','angal.admission.newpatient','x','N','admission','none','N',0);
insert into menuitem values ('btnadmedit','angal.admission.editpatient','angal.admission.editpatient','x','E','admission','none','N',1);
insert into menuitem values ('btnadmopd','angal.admission.opd','angal.admission.admission','x','O','admission','none','N',5);
insert into menuitem values ('btnadmadm','angal.admission.admission','angal.admission.admission','x','A','admission','none','N',4);
insert into menuitem values ('btnadmdel','angal.admission.deletepatient','angal.admission.deletepatient','x','L','admission','none','N',2);
insert into menuitem values ('btnadmmer','angal.admission.merge','angal.admission.merge','x','L','admission','none','N',2);
insert into menuitem values ('btndataeditpat','angal.admission.editpatient','angal.admission.editpatient','x','P','data','none','N',0);
insert into menuitem values ('btndatamalnut','angal.admission.malnutritioncontrol','angal.admission.malnutritioncontrol','x','M','data','none','N',3);
insert into menuitem values ('btndatadel','angal.admission.deletem','angal.admission.deletem','x','D','data','none','N',2);
insert into menuitem values ('btndataedit','angal.admission.editm','angal.admission.editm','x','E','data','none','N',1);
insert into menuitem values ('btnopddel','angal.opd.delete','angal.opd.delete','x','D','opd','none','N',2);
insert into menuitem values ('btnopdedit','angal.opd.edit','angal.opd.edit','x','E','opd','none','N',1);
insert into menuitem values ('btnopdnew','angal.opd.new','angal.opd.new','x','N','opd','none','N',0);
insert into menuitem values ('btnpharmaceuticaldel','angal.medicals.delete','angal.medicals.delete','x','D','medicals','none','N',2);
insert into menuitem values ('btnpharmaceuticaledit','angal.medicals.edit','angal.medicals.edit','x','E','medicals','none','N',1);
insert into menuitem values ('btnpharmaceuticalnew','angal.medicals.new','angal.medicals.new','x','N','medicals','none','N',0);
insert into menuitem values ('btnlaboratorydel','angal.lab.delete','angal.lab.delete','x','D','laboratory','none','N',2);
insert into menuitem values ('btnlaboratoryedit','angal.lab.edit','angal.lab.edit','x','E','laboratory','none','N',1);
insert into menuitem values ('btnlaboratorynew','angal.lab.new','angal.lab.new','x','N','laboratory','none','N',0);

insert into usergroup values("guest","Read Only Users");
insert into user values("guest","guest","guest","guest");

insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','data','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnadmdel','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnadmadm','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnadmedit','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnadmnew','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnadmopd','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnadmmer','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnlaboratorydel','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnlaboratoryedit','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnlaboratorynew','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnopdedit','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnopddel','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnopdnew','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btndatamalnut','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btndatadel','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btndataedit','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btndataeditpat','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnpharmaceuticaldel','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnpharmaceuticaledit','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('admin','btnpharmaceuticalnew','Y');

insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','admtype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','disctype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','admission','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','disease','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','exams','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','exit','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','file','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','generaldata','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','groups','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','help','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','hospital','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','laboratory','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','medicals','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','medicalstock','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','operation','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','pharmacy','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','statistics','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','opd','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','users','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','usersusers','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','vaccine','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','ward','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','types','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','pretreatmenttype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','diseasetype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','medstockmovtype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','examtype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','operationtype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','deliverytype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','medicalstype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','delresulttype','N');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','printing','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','examlist1','Y');
insert into groupmenu (gm_ug_id_a, gm_mni_id_a, gm_active) values ('guest','diseaselist','Y');
