CREATE TABLE OH_PARTNERTYPES (
  PRTT_CODE VARCHAR(20) NOT NULL,
  PRTT_DESCRIPTION VARCHAR(255) NOT NULL,
  PRTT_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  PRTT_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
  PRTT_CREATED_DATE DATETIME NULL DEFAULT NULL,
  PRTT_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  PRTT_LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  PRTT_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (PRTT_CODE)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;
