CREATE TABLE OH_PREGNANCYDELIVERY (

    PRGDLV_ID INT(11) NOT NULL AUTO_INCREMENT,

    PRGDLV_PRG_ID INT(11) NOT NULL UNIQUE,
    PRGDLV_TYPE_ID INT(11) NOT NULL,

    PRGDLV_LABOR_ONSET_DATETIME DATETIME,
    ROM_DATETIME DATETIME,
    PRGDLV_DATE DATETIME NOT NULL,

    PRGDLV_DELIVERYMODE VARCHAR(50),
    PRGDLV_INDICATION VARCHAR(200),
    PRGDLV_ANESTHESIA_USED VARCHAR(100),
    PRGDLV_PERINEAL_INTEGRITY VARCHAR(100),

    PRGDLV_PLACENTA_COMPLETE TINYINT(1) DEFAULT 0,
    PRGDLV_PLACENTA_WEIGHT INT(11),
    PRGDLV_ESTIMATED_BLD_LOSS INT(11),

    PRGDLV_ATTENDING_CLINICIAN_ID VARCHAR(50),

    PRGDLV_FATHER_NAME VARCHAR(100),
    PRGDLV_FATHER_AGE INT(11),
    PRGDLV_FATHER_BIRTHPLACE VARCHAR(100),
    PRGDLV_FATHER_ADDRESS VARCHAR(200),
    PRGDLV_FATHER_PROFESSION VARCHAR(100),

    PRGDLV_CREATED_BY VARCHAR(50) NOT NULL,
    PRGDLV_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRGDLV_LAST_MODIFIED_BY VARCHAR(50),
    PRGDLV_LAST_MODIFIED_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRGDLV_ACTIVE BOOLEAN DEFAULT TRUE,
    PRGDLV_LOCK INT(11) DEFAULT 0,

    PRIMARY KEY (PRGDLV_ID),

    CONSTRAINT FK_DELIVERY_PREGNANCY
        FOREIGN KEY (PRGDLV_PRG_ID)
        REFERENCES OH_PREGNANCY(PRG_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT FK_DELIVERY_TYPE
        FOREIGN KEY (PRGDLV_TYPE_ID)
        REFERENCES OH_PREGNANCYDELIVERYTYPE(PRGDLVT_ID),

    INDEX idx_delivery_type (PRGDLV_TYPE_ID)

) ENGINE = INNODB;