-- =============================================
-- Table: OH_STAFF
-- =============================================
CREATE TABLE IF NOT EXISTS OH_STAFF (
    STF_ID                  INT AUTO_INCREMENT PRIMARY KEY,
    STF_CODE                VARCHAR(20)  NOT NULL,
    STF_FIRST_NAME          VARCHAR(50)  NOT NULL,
    STF_LAST_NAME           VARCHAR(50)  NOT NULL,
    STF_PROFESSION          VARCHAR(50)  DEFAULT NULL,
    STF_PHONE               VARCHAR(50)  DEFAULT NULL,
    STF_IS_ACTIVE           TINYINT(1)   NOT NULL DEFAULT 1,
    STF_CREATED_BY          VARCHAR(50)  DEFAULT NULL,
    STF_CREATED_DATE        DATETIME     DEFAULT NULL,
    STF_LAST_MODIFIED_BY    VARCHAR(50)  DEFAULT NULL,
    STF_LAST_MODIFIED_DATE  DATETIME     DEFAULT NULL,
    STF_LOCK                INT          DEFAULT 0,
    UNIQUE KEY UK_STAFF_CODE (STF_CODE),
    KEY IDX_STAFF_NAME (STF_LAST_NAME, STF_FIRST_NAME),
    KEY IDX_STAFF_PROFESSION (STF_PROFESSION)
    ) ENGINE=InnoDB;