CREATE TABLE OH_NEWBORN (
    NBN_ID INT(11) NOT NULL AUTO_INCREMENT,
    NBN_DLV_ID INT(11) NOT NULL,

    NBN_NAME VARCHAR(100) NOT NULL,
    NBN_NEONATAL_STATUS VARCHAR(20),
    NBN_BIRTH_DATE DATETIME,

    NBN_BIRTH_ORDER VARCHAR(50),
    NBN_GENDER CHAR(1),

    NBN_BIRTH_WEIGHT DOUBLE NOT NULL,
    NBN_BIRTH_LENGTH DOUBLE,
    NBN_HEAD_CIRCUMFERENCE DOUBLE,

    NBN_APGAR_SCORE_1MIN INT(11),
    NBN_APGAR_SCORE_5MIN INT(11),

    NBN_RESUSCITATION_REQUIRED TINYINT(1),
    NBN_CRY_TIME VARCHAR(50),

    NBN_CONGENITAL_ANOMALIES LONGTEXT,

    NBN_HIV_STATUS CHAR(1),

    NBN_CREATED_BY VARCHAR(50),
    NBN_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    NBN_LAST_MODIFIED_BY VARCHAR(50),
    NBN_LAST_MODIFIED_DATE DATETIME,

    NBN_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,

    NBN_LOCK INT(11) DEFAULT 0,

    PRIMARY KEY (NBN_ID),

    CONSTRAINT FK_NEWBORN_DELIVERY
        FOREIGN KEY (NBN_DLV_ID)
        REFERENCES OH_PREGNANCYDELIVERY(PRGDLV_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    INDEX idx_newborn_delivery (NBN_DLV_ID)
) ENGINE=InnoDB;