-- Drop the existing table
DROP TABLE IF EXISTS OH_PREGNANCYVISITTYPE;

-- Create Visit Type table
CREATE TABLE OH_PREGNANCYVISITTYPE (
    PVT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PVT_CODE VARCHAR(20) NOT NULL UNIQUE,
    PVT_DESCRIPTION VARCHAR(255) NOT NULL,

    -- Audit fields (JPA aligned)
    PVT_CREATED_BY VARCHAR(50) NOT NULL,
    PVT_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PVT_LAST_MODIFIED_BY VARCHAR(50),
    PVT_LAST_MODIFIED_DATE DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP

) ENGINE = INNODB DEFAULT CHARACTER SET utf8;