ALTER TABLE OH_OPD
    ADD COLUMN IF NOT EXISTS OPD_REFERING_HOSP VARCHAR(255),
    ADD COLUMN IF NOT EXISTS OPD_RECEIVING_HOSP VARCHAR(255),
    ADD COLUMN IF NOT EXISTS OPD_MALNUTRITION TINYINT(1) DEFAULT 0 COMMENT 'Malnutrition status (1=Yes, 0=No)',
    ADD COLUMN IF NOT EXISTS OPD_REFERING_MOTIF VARCHAR(255) DEFAULT NULL COMMENT 'Referral reason (motif)';