ALTER TABLE OH_PATIENTEXAMINATION
   ADD COLUMN c DOUBLE DEFAULT NULL,
   ADD COLUMN PEX_WEIGHT_AGE VARCHAR(255) DEFAULT NULL,
   ADD COLUMN PEX_HEIGHT_AGE DOUBLE DEFAULT NULL,
   ADD COLUMN PEX_BODY_MASS_INDEX_AGE DOUBLE DEFAULT NULL;