ALTER TABLE OH_MEDICALDSR 
ADD COLUMN MDSR_CONDITIONING VARCHAR(100) NULL DEFAULT NULL AFTER MDSR_OUT_QTI,
ADD COLUMN MDSR_SHAPE VARCHAR(100) NULL DEFAULT NULL AFTER MDSR_CONDITIONING,
ADD COLUMN MDSR_DOSING VARCHAR(255) NULL DEFAULT NULL AFTER MDSR_SHAPE;